//go:build js && wasm
// +build js,wasm

package main

import (
	"fmt"

	"github.com/monstercameron/GoWebComponents/html"
	"github.com/monstercameron/GoWebComponents/ui"
	"github.com/monstercameron/GoWebComponents/utils"
)

func App() ui.Node {
	parseCount := ui.UseState(0)
	parseCurrentCount := parseCount.Get()

	parseIncrement := ui.UseEvent(func() {
		parseCount.Update(func(previous int) int { return previous + 1 })
	})

	parseRouteSegment := ui.UseState("home")
	parseShowHomeRoute := ui.UseEvent(func() {
		parseRouteSegment.Set("home")
	})
	parseShowDashboardRoute := ui.UseEvent(func() {
		parseRouteSegment.Set("dashboard")
	})
	parseShowSettingsRoute := ui.UseEvent(func() {
		parseRouteSegment.Set("settings")
	})
	parseCurrentRoute := parseRouteSegment.Get()

	parseFormSubmitted := ui.UseState(false)
	parseSubmitStarterForm := ui.UseEvent(func() {
		parseFormSubmitted.Set(true)
	})
	resetStarterForm := ui.UseEvent(func() {
		parseFormSubmitted.Set(false)
	})
	parseFormStatus := "Draft not submitted yet."
	if parseFormSubmitted.Get() {
		parseFormStatus = "Last submit marked complete."
	}

	parseDataStatus := ui.UseState("idle")
	parseRefreshStarterData := ui.UseEvent(func() {
		parseDataStatus.Update(func(previous string) string {
			switch previous {
			case "idle":
				return "loading"
			case "loading":
				return "ready"
			default:
				return "refreshing"
			}
		})
	})
	parseCurrentDataStatus := parseDataStatus.Get()

	parseTeamCount := ui.UseState(3)
	parseAddTeammate := ui.UseEvent(func() {
		parseTeamCount.Update(func(previous int) int { return previous + 1 })
	})
	parseCurrentTeamCount := parseTeamCount.Get()

	return html.Div(html.Props{Class: "shell"},
		html.Div(html.Props{Class: "panel"},
			html.Div(html.Props{Class: "brand-row"},
				html.Div(html.Props{Class: "brand-mark"}, html.Text("GWC")),
				html.Div(html.Props{},
					html.P(html.Props{Class: "eyebrow"}, html.Text("GoWebComponents Starter")),
					html.P(html.Props{Class: "brand-copy"}, html.Text("Dark-mode starter scaffold generated by gwc start")),
				),
			),
			html.H1(html.Props{}, html.Text("golden-reference-app")),
			html.P(html.Props{Class: "lede"}, html.Text("Golden output for the reference app scaffold.")),
			html.Div(html.Props{Class: "meta-grid"},
				html.Div(html.Props{Class: "meta-card"},
					html.Span(html.Props{Class: "meta-label"}, html.Text("Author")),
					html.Strong(html.Props{}, html.Text("Golden Test")),
				),
				html.Div(html.Props{Class: "meta-card"},
					html.Span(html.Props{Class: "meta-label"}, html.Text("Version")),
					html.Strong(html.Props{}, html.Text("1.0.0")),
				),
				html.Div(html.Props{Class: "meta-card"},
					html.Span(html.Props{Class: "meta-label"}, html.Text("Preset")),
					html.Strong(html.Props{}, html.Text("Reference App")),
				),
				html.Div(html.Props{Class: "meta-card"},
					html.Span(html.Props{Class: "meta-label"}, html.Text("Module")),
					html.Strong(html.Props{}, html.Text("github.com/example/golden-reference-app")),
				),
			),
			html.P(html.Props{Class: "lede"}, html.Text("Generated in golden tests.")),
			html.P(html.Props{Class: "meta"}, html.Text("Features: router, forms, fetch, state, browser-tests")),
			html.H2(html.Props{Class: "feature-heading"}, html.Text("Starter capability matrix")),
			html.Div(html.Props{Class: "feature-grid"},
				html.Div(html.Props{Class: "feature-card"},
					html.Span(html.Props{Class: "feature-tag"}, html.Text("Router")),
					html.P(html.Props{Class: "feature-copy"}, html.Text("Route shell and navigation affordances are scaffolded in the starter layout.")),
				),
				html.Div(html.Props{Class: "feature-card"},
					html.Span(html.Props{Class: "feature-tag"}, html.Text("Forms")),
					html.P(html.Props{Class: "feature-copy"}, html.Text("Starter form interactions are scaffolded so teams can extend typed form state deliberately.")),
				),
				html.Div(html.Props{Class: "feature-card"},
					html.Span(html.Props{Class: "feature-tag"}, html.Text("Fetch")),
					html.P(html.Props{Class: "feature-copy"}, html.Text("Async resource ownership is called out for data-loading and mutation setup.")),
				),
				html.Div(html.Props{Class: "feature-card"},
					html.Span(html.Props{Class: "feature-tag"}, html.Text("State")),
					html.P(html.Props{Class: "feature-copy"}, html.Text("Shared state ownership is planned as a first-class concern in this scaffold.")),
				),
				html.Div(html.Props{Class: "feature-card"},
					html.Span(html.Props{Class: "feature-tag"}, html.Text("Browser Tests")),
					html.P(html.Props{Class: "feature-copy"}, html.Text("Playwright-Go smoke-test scaffolding is generated under test/playwrightgo.")),
				),
			),
			html.Div(html.Props{Class: "capability"},
				html.Span(html.Props{Class: "capability-title"}, html.Text("Routing")),
				html.P(html.Props{Class: "capability-copy"}, html.Text(fmt.Sprintf("Active route: %s", parseCurrentRoute))),
				html.Div(html.Props{Class: "capability-actions"},
					html.Button(html.Props{Class: "capability-button", OnClick: parseShowHomeRoute}, html.Text("Home")),
					html.Button(html.Props{Class: "capability-button", OnClick: parseShowDashboardRoute}, html.Text("Dashboard")),
					html.Button(html.Props{Class: "capability-button", OnClick: parseShowSettingsRoute}, html.Text("Settings")),
				),
			),
			html.Div(html.Props{Class: "capability"},
				html.Span(html.Props{Class: "capability-title"}, html.Text("Async Data")),
				html.P(html.Props{Class: "capability-copy"}, html.Text(fmt.Sprintf("Data status: %s", parseCurrentDataStatus))),
				html.Button(html.Props{Class: "capability-button", OnClick: parseRefreshStarterData}, html.Text("Advance data sync state")),
			),
			html.Div(html.Props{Class: "capability"},
				html.Span(html.Props{Class: "capability-title"}, html.Text("Shared State")),
				html.P(html.Props{Class: "capability-copy"}, html.Text(fmt.Sprintf("Team members tracked: %d", parseCurrentTeamCount))),
				html.Button(html.Props{Class: "capability-button", OnClick: parseAddTeammate}, html.Text("Add teammate")),
			),
			html.Form(html.Props{Class: "capability"},
				html.Span(html.Props{Class: "capability-title"}, html.Text("Forms")),
				html.P(html.Props{Class: "capability-copy"}, html.Text(parseFormStatus)),
				html.Label(html.Props{}, html.Text("Email")),
				html.Input(html.Props{Type: "email", Placeholder: "you@example.com", Class: "capability-input"}),
				html.Div(html.Props{Class: "capability-actions"},
					html.Button(html.Props{Class: "capability-button", Type: "button", OnClick: parseSubmitStarterForm}, html.Text("Submit")),
					html.Button(html.Props{Class: "capability-button", Type: "button", OnClick: resetStarterForm}, html.Text("Reset")),
				),
			),
			html.Div(html.Props{Class: "counter"}, html.Text(fmt.Sprintf("Count: %d", parseCurrentCount))),
			html.Button(html.Props{OnClick: parseIncrement, Class: "button"}, html.Text("Increment")),
		),
	)
}

func main() {
	utils.DisableAllDebug()
	ui.Render(ui.CreateElement(App), "#app")
	select {}
}
