package main

import (
	"fmt"
	"path"
	"strings"

	gwchtml "github.com/monstercameron/GoWebComponents/html"
	. "github.com/monstercameron/GoWebComponents/html/shorthand"
	"github.com/monstercameron/GoWebComponents/ui"
)

// renderLandingPage builds the site home: hero, live demo, stats, features.
func renderLandingPage(parseHeroSource string, parseExampleCount int, parseChapterCount int) ui.Node {
	parseChrome := pageChrome{
		Title:       "GoWebComponents — Go-native UIs for the browser",
		Description: "Build React-class web UIs in pure Go: fine-grained reactivity, SSR with hydration, a 304ms hot-reload loop, and crash containment built in.",
		RootPrefix:  ".",
		ActiveNav:   "home",
	}
	return renderPage(parseChrome,
		Main(Class("container"),
			Section(Class("hero"),
				H1(Text("Go. In the "), Span(Class("hero-accent"), Text("browser")), Text(".")),
				P(Class("hero-sub"),
					Text("Build React-class web UIs in pure Go — fine-grained reactivity, server-side rendering with hydration, and a type system you already trust. No JavaScript toolchain required.")),
				Div(Class("hero-ctas"),
					A(Class("button-primary"), Href("learn/01-getting-started/index.html"), Text("Get started")),
					A(Class("button-secondary"), Href("examples/index.html"), Textf("Browse %d live examples", parseExampleCount)),
				),
				Div(Class("hero-demo"),
					Div(Class("demo-pane"),
						Div(Class("demo-pane-title"), Text("counter/main.go")),
						Pre(Code(Text(parseHeroSource))),
					),
					Div(Class("demo-pane"),
						Div(Class("demo-pane-title"), Span(Class("live-dot")), Text(" live — running in wasm")),
						Iframe(Src("public-examples-site/assets/examples/counter/index.html"),
							Attr("title", "Live counter example"), Attr("loading", "lazy")),
					),
				),
				Div(Class("stats-strip"),
					renderStat("6/6", "paint benchmarks won vs React", "browser-measured update scenarios"),
					renderStat("~1.4 MB", "over the wire", "production wasm, brotli compressed"),
					renderStat("304 ms", "edit-to-browser reload", "dev server rebuild + fine-grained hot reload"),
					renderStat("0 allocs", "steady-state reconcile", "keyed list diff hot path"),
				),
			),

			H2(Class("section-title"), Text("Why teams pick it")),
			P(Class("section-sub"), Text("One language for backend and frontend, with the engineering posture of a systems runtime — not a script loader.")),
			Div(Class("feature-grid"),
				renderFeature("Fine-grained reactivity", "Solid-style atoms update exactly the DOM nodes that depend on them. Components re-render only when their own state changes.", "learn/06-state-and-reactivity/index.html", "State & reactivity"),
				renderFeature("SSR + hydration", "Render on the server, ship real HTML, hydrate in place with identity reuse and per-subtree mismatch recovery. This site's docs are prerendered with it.", "learn/09-ssr-and-hydration/index.html", "SSR & hydration"),
				renderFeature("Crash containment", "A panicking component produces a structured, agent-readable console report — and the page keeps running. Goroutines, callbacks, and renders are all guarded.", "learn/12-devtools-testing-and-observability/index.html", "Observability"),
				renderFeature("A real dev loop", "File watching, incremental wasm rebuilds, CSS swap without reload, and component-state-preserving hot reload — measured at 304 ms end to end.", "learn/02-gwc-workflows/index.html", "Workflows"),
				renderFeature("Router, forms, i18n", "Nested routes with loaders and guards, controlled forms with validation and CSRF, locale routing and message catalogs — in the box.", "learn/08-routing/index.html", "Routing"),
				renderFeature("Testable by design", "A public testkit renders components headlessly, drives hooks, and asserts SSR output. The framework itself ships with thousands of native + wasm + browser tests.", "learn/12-devtools-testing-and-observability/index.html", "Testing"),
			),

			H2(Class("section-title"), Text("Learn it in an afternoon")),
			P(Class("section-sub"), Textf("A guided, %d-chapter manual takes you from first render to scaling patterns — every page statically generated by the framework's own SSR.", parseChapterCount)),
			Div(Class("hero-ctas"),
				A(Class("button-primary"), Href("learn/index.html"), Text("Open the manual")),
				A(Class("button-secondary"), Href("api/index.html"), Text("API reference")),
			),
		),
	)
}

func renderStat(parseValue string, parseLabel string, parseNote string) ui.Node {
	return Div(Class("stat-card"),
		Div(Class("stat-value"), Text(parseValue)),
		Div(Class("stat-label"), Text(parseLabel)),
		Div(Class("stat-note"), Text(parseNote)),
	)
}

func renderFeature(parseTitle string, parseBody string, parseHref string, parseLinkLabel string) ui.Node {
	return Div(Class("feature-card"),
		H3(Text(parseTitle)),
		P(Text(parseBody)),
		A(Class("feature-link"), Href(parseHref), Textf("%s →", parseLinkLabel)),
	)
}

// markdownProseClasses maps markdown output onto the site design system. The
// prose container styles semantic tags, so only code labels need classes.
var markdownProseClasses = gwchtml.MarkdownClasses{}

// renderChapterPage builds one reference-manual chapter page.
func renderChapterPage(parseChapters []chapter, parseIndex int) ui.Node {
	parseChapter := parseChapters[parseIndex]
	parseChrome := pageChrome{
		Title:       parseChapter.Title + " — GoWebComponents",
		Description: parseChapter.Summary,
		RootPrefix:  "../..",
		ActiveNav:   "learn",
	}

	parseBody := gwchtml.RenderMarkdown(parseChapter.Markdown, gwchtml.MarkdownRenderOptions{
		SourcePath: parseChapter.Slug + ".md",
		Classes:    markdownProseClasses,
		ResolveHref: func(parseSourcePath, parseDestination string) string {
			return resolveChapterHref(parseDestination)
		},
	})

	var parsePagerNodes []ui.Node
	if parseIndex > 0 {
		parsePrevious := parseChapters[parseIndex-1]
		parsePagerNodes = append(parsePagerNodes, A(Href("../"+parsePrevious.Slug+"/index.html"),
			Span(Class("pager-label"), Text("Previous")), Text(parsePrevious.Title)))
	} else {
		parsePagerNodes = append(parsePagerNodes, Span())
	}
	if parseIndex < len(parseChapters)-1 {
		parseNext := parseChapters[parseIndex+1]
		parsePagerNodes = append(parsePagerNodes, A(Class("pager-next"), Href("../"+parseNext.Slug+"/index.html"),
			Span(Class("pager-label"), Text("Next")), Text(parseNext.Title)))
	}

	return renderPage(parseChrome,
		Main(Class("container"),
			Div(Class("learn-layout"),
				renderLearnSidebar(parseChapters, parseChapter.Slug, ".."),
				Div(
					Article(append([]interface{}{Class("prose")}, nodesToArgs(parseBody)...)...),
					Div(Class("chapter-pager"), parsePagerNodes[0], parsePagerNodes[len(parsePagerNodes)-1]),
				),
			),
		),
	)
}

// resolveChapterHref rewrites chapter-to-chapter markdown links to site URLs.
func resolveChapterHref(parseDestination string) string {
	parseTrimmed := strings.TrimSpace(parseDestination)
	if strings.HasPrefix(parseTrimmed, "http") || strings.HasPrefix(parseTrimmed, "#") {
		return parseTrimmed
	}
	parseBase, parseFragment, _ := strings.Cut(parseTrimmed, "#")
	if strings.HasSuffix(parseBase, ".md") && !strings.Contains(parseBase, "/") {
		parseSlug := strings.TrimSuffix(strings.TrimPrefix(parseBase, "./"), ".md")
		parseResolved := "../" + parseSlug + "/index.html"
		if parseFragment != "" {
			parseResolved += "#" + parseFragment
		}
		return parseResolved
	}
	// Repo-relative links (source files, example dirs, other docs) cannot be
	// served from the static site; send them to the repository instead.
	parseRepoPath := path.Clean(path.Join("docs/REFERENCE_MANUAL", parseBase))
	parseResolved := "https://github.com/monstercameron/GoWebComponents/blob/master/" + parseRepoPath
	if parseFragment != "" {
		parseResolved += "#" + parseFragment
	}
	return parseResolved
}

// renderLearnSidebar lists every chapter with the active one highlighted.
func renderLearnSidebar(parseChapters []chapter, parseActiveSlug string, parseLearnPrefix string) ui.Node {
	parseLinks := []interface{}{Class("learn-sidebar"),
		Div(Class("sidebar-group"), Text("Reference manual"))}
	for _, parseChapter := range parseChapters {
		parseAttrs := []interface{}{Href(parseLearnPrefix + "/" + parseChapter.Slug + "/index.html"), Text(chapterShortTitle(parseChapter))}
		if parseChapter.Slug == parseActiveSlug {
			parseAttrs = append(parseAttrs, Attr("data-active", "true"))
		}
		parseLinks = append(parseLinks, A(parseAttrs...))
	}
	return Aside(parseLinks...)
}

// chapterShortTitle strips numeric prefixes for sidebar display.
func chapterShortTitle(parseChapter chapter) string {
	parseTitle := parseChapter.Title
	if parseCut := strings.Index(parseTitle, ": "); parseCut > 0 && parseCut < 14 {
		parseTitle = parseTitle[parseCut+2:]
	}
	return parseTitle
}

// renderLearnIndex builds the chapter listing page.
func renderLearnIndex(parseChapters []chapter, parseConcepts []catalogItem) ui.Node {
	parseChrome := pageChrome{
		Title:       "Learn GoWebComponents",
		Description: "The guided reference manual: from first render to scaling patterns.",
		RootPrefix:  "..",
		ActiveNav:   "learn",
	}

	parseChapterCards := []interface{}{Class("card-grid")}
	for parseIndex, parseChapter := range parseChapters {
		parseChapterCards = append(parseChapterCards, Div(Class("catalog-card"),
			H3(A(Href(parseChapter.Slug+"/index.html"), Textf("%02d · %s", parseIndex+1, chapterShortTitle(parseChapter)))),
			P(Text(parseChapter.Summary)),
		))
	}

	parseConceptCards := []interface{}{Class("card-grid")}
	for _, parseConcept := range parseConcepts {
		parseConceptCards = append(parseConceptCards, Div(Class("catalog-card"),
			H3(A(Href("concepts/"+slugify(parseConcept.Title)+"/index.html"), Text(parseConcept.Title))),
			P(Text(parseConcept.Blurb)),
			Div(Class("card-meta"),
				Span(Class("chip chip-level"), Text(parseConcept.Level)),
				Span(Class("chip"), Text(parseConcept.Module)),
			),
		))
	}

	return renderPage(parseChrome,
		Main(Class("container"),
			H1(Class("page-title"), Text("Learn")),
			P(Class("page-sub"), Text("Start with the guided manual — sixteen chapters from first render to large-codebase patterns. Deep-dive concept guides cover individual subsystems.")),
			H2(Class("section-title"), Text("The manual")),
			Div(parseChapterCards...),
			H2(Class("section-title"), Text("Concept guides")),
			P(Class("section-sub"), Text("Focused documents on one subsystem at a time.")),
			Div(parseConceptCards...),
		),
	)
}

// renderConceptPage builds one concept guide from its markdown source or the
// inline catalog sections when no source document exists.
// parseConceptSlugsByDoc maps a doc filename (e.g. "logging.md") to its
// concept page slug so doc-to-doc links resolve to sibling pages.
func renderConceptPage(parseConcept catalogItem, parseMarkdown string, parseConceptSlugsByDoc map[string]string) ui.Node {
	parseChrome := pageChrome{
		Title:       parseConcept.Title + " — GoWebComponents",
		Description: parseConcept.Blurb,
		RootPrefix:  "../../..",
		ActiveNav:   "learn",
	}

	var parseBody []ui.Node
	if parseMarkdown != "" {
		parseBody = gwchtml.RenderMarkdown(parseMarkdown, gwchtml.MarkdownRenderOptions{
			SourcePath: parseConcept.Content.SourcePath,
			Classes:    markdownProseClasses,
			ResolveHref: func(parseSourcePath, parseDestination string) string {
				return resolveConceptHref(parseDestination, parseConceptSlugsByDoc)
			},
		})
	} else {
		parseBody = append(parseBody, H1(Text(parseConcept.Title)))
		for _, parseSection := range parseConcept.Content.Sections {
			if parseSection.Heading != "" {
				parseBody = append(parseBody, H2(Text(parseSection.Heading)))
			}
			for _, parseParagraph := range parseSection.Paragraphs {
				parseBody = append(parseBody, P(Text(parseParagraph)))
			}
		}
	}

	return renderPage(parseChrome,
		Main(Class("container"),
			Article(append([]interface{}{Class("prose"), Style(map[string]string{"padding-top": "40px"})}, nodesToArgs(parseBody)...)...),
		),
	)
}

// resolveConceptHref rewrites concept-doc markdown links: sibling doc links
// become concept pages, everything else repo-relative goes to GitHub.
func resolveConceptHref(parseDestination string, parseConceptSlugsByDoc map[string]string) string {
	parseTrimmed := strings.TrimSpace(parseDestination)
	if parseTrimmed == "" || strings.HasPrefix(parseTrimmed, "http") || strings.HasPrefix(parseTrimmed, "#") {
		return parseTrimmed
	}
	parseBase, parseFragment, _ := strings.Cut(parseTrimmed, "#")
	if strings.HasSuffix(parseBase, ".md") {
		parseDocName := path.Base(parseBase)
		if parseSlug, isParseKnown := parseConceptSlugsByDoc[parseDocName]; isParseKnown {
			parseResolved := "../" + parseSlug + "/index.html"
			if parseFragment != "" {
				parseResolved += "#" + parseFragment
			}
			return parseResolved
		}
	}
	parseRepoPath := path.Clean(path.Join("examples/public-examples-site/assets/docs", parseBase))
	parseResolved := "https://github.com/monstercameron/GoWebComponents/blob/master/" + parseRepoPath
	if parseFragment != "" {
		parseResolved += "#" + parseFragment
	}
	return parseResolved
}

// renderExamplesGallery builds the filterable example gallery.
func renderExamplesGallery(parseExamples []catalogItem) ui.Node {
	parseChrome := pageChrome{
		Title:       "Examples — GoWebComponents",
		Description: "Live, runnable examples for every framework feature, each with mirrored Go source.",
		RootPrefix:  "..",
		ActiveNav:   "examples",
	}

	parseModuleSet := map[string]bool{}
	for _, parseExample := range parseExamples {
		parseModuleSet[parseExample.Module] = true
	}
	parseFilterChips := []interface{}{Class("filter-bar"),
		Button(Class("filter-chip"), Attr("type", "button"), Attr("data-filter", "all"), Attr("data-active", "true"), Text("All"))}
	for _, parseModule := range sortedKeys(parseModuleSet) {
		parseFilterChips = append(parseFilterChips,
			Button(Class("filter-chip"), Attr("type", "button"), Attr("data-filter", parseModule), Text(parseModule)))
	}

	parseCards := []interface{}{Class("card-grid")}
	for _, parseExample := range parseExamples {
		parseActions := []interface{}{Class("card-actions")}
		if parseExample.Content.PreviewPath != "" {
			parseActions = append(parseActions,
				A(Href("../public-examples-site/"+parseExample.Content.PreviewPath), Attr("target", "_blank"), Text("Run live →")))
		}
		if parseExample.Content.SourcePath != "" {
			parseActions = append(parseActions,
				A(Href("../public-examples-site/"+parseExample.Content.SourcePath), Attr("target", "_blank"), Text("Source")))
		}
		parseCards = append(parseCards, Div(Class("catalog-card"), Attr("data-module", parseExample.Module),
			H3(Text(parseExample.Title)),
			P(Text(parseExample.Blurb)),
			Div(Class("card-meta"),
				Span(Class("chip chip-level"), Text(parseExample.Level)),
				Span(Class("chip"), Text(parseExample.Module)),
			),
			Div(parseActions...),
		))
	}

	return renderPage(parseChrome,
		Main(Class("container"),
			H1(Class("page-title"), Textf("%d live examples", len(parseExamples))),
			P(Class("page-sub"), Text("Every example runs real wasm in your browser and ships with its mirrored Go source. Filter by subsystem, run anything, copy everything.")),
			Div(parseFilterChips...),
			Div(parseCards...),
		),
	)
}

// renderAPIIndex builds the API reference landing page from catalog API groups.
func renderAPIIndex(parseAPIItems []catalogItem) ui.Node {
	parseChrome := pageChrome{
		Title:       "API Reference — GoWebComponents",
		Description: "The public API surface, grouped by subsystem.",
		RootPrefix:  "..",
		ActiveNav:   "api",
	}

	parseCards := []interface{}{Class("card-grid")}
	for _, parseItem := range parseAPIItems {
		parseHref := "../public-examples-site/" + parseItem.Content.SourcePath
		if parseItem.Content.AnchorID != "" {
			parseHref += "#" + parseItem.Content.AnchorID
		}
		parseTagLine := strings.Join(parseItem.SearchTags, " · ")
		if len(parseTagLine) > 110 {
			parseTagLine = parseTagLine[:107] + "..."
		}
		parseCards = append(parseCards, Div(Class("catalog-card"),
			H3(A(Href(parseHref), Text(parseItem.Title))),
			P(Text(parseItem.Content.Summary)),
			Div(Class("card-meta"), Span(Class("chip"), Text(parseTagLine))),
		))
	}

	return renderPage(parseChrome,
		Main(Class("container"),
			H1(Class("page-title"), Text("API reference")),
			P(Class("page-sub"), Text("The public surface grouped by subsystem. Each group links into the full generated reference with signatures and parameter tables.")),
			Div(parseCards...),
			P(Class("section-sub"), Style(map[string]string{"margin-top": "32px"}),
				Text("Prefer browsing interactively? The "),
				A(Href("../public-examples-site/index.html"), Text("interactive catalog")),
				Text(" runs the full docs app as wasm with live filtering and embedded demos."),
			),
		),
	)
}

// nodesToArgs adapts a ui.Node slice for variadic shorthand constructors.
func nodesToArgs(parseNodes []ui.Node) []interface{} {
	parseArgs := make([]interface{}, len(parseNodes))
	for parseIndex, parseNode := range parseNodes {
		parseArgs[parseIndex] = parseNode
	}
	return parseArgs
}

// sortedKeys returns map keys in sorted order.
func sortedKeys(parseSet map[string]bool) []string {
	parseKeys := make([]string, 0, len(parseSet))
	for parseKey := range parseSet {
		parseKeys = append(parseKeys, parseKey)
	}
	for parseA := 0; parseA < len(parseKeys); parseA++ {
		for parseB := parseA + 1; parseB < len(parseKeys); parseB++ {
			if parseKeys[parseB] < parseKeys[parseA] {
				parseKeys[parseA], parseKeys[parseB] = parseKeys[parseB], parseKeys[parseA]
			}
		}
	}
	return parseKeys
}

var _ = fmt.Sprintf
