// Code generated by `gwc css gen`; DO NOT EDIT.

package typedcsstokensdemo

import "github.com/monstercameron/GoWebComponents/v4/css/u"

// Typed, compile-checked token constants for the application theme.
// A typo in a color/size/radius/spacing token is now a compile error, and the
// full token set autocompletes. Pass these to u.BgC/u.TextC/u.TextSize/etc.

const (
	ColorBrand50  u.ColorToken = "brand-50"
	ColorBrand500 u.ColorToken = "brand-500"
	ColorBrand900 u.ColorToken = "brand-900"
	ColorInk      u.ColorToken = "ink"
	TextDisplay   u.TextScale  = "display"
	RadiusPill    u.Radius     = "pill"
	Spacing7      u.Spacing    = 7
	Spacing9      u.Spacing    = 9
)
