//go:build js && wasm
// +build js,wasm

package main

import (
	"fmt"

	"github.com/monstercameron/GoWebComponents/html"
	"github.com/monstercameron/GoWebComponents/ui"
	"github.com/monstercameron/GoWebComponents/utils"
)

func App() ui.Node {
	parseCount := ui.UseState(0)
	parseCurrentCount := parseCount.Get()

	parseIncrement := ui.UseEvent(func() {
		parseCount.Update(func(previous int) int { return previous + 1 })
	})



	return html.Div(html.Props{Class: "shell"},
		html.Div(html.Props{Class: "panel"},
			html.Div(html.Props{Class: "brand-row"},
				html.Div(html.Props{Class: "brand-mark"}, html.Text("GWC")),
				html.Div(html.Props{},
					html.P(html.Props{Class: "eyebrow"}, html.Text("GoWebComponents Starter")),
					html.P(html.Props{Class: "brand-copy"}, html.Text("Dark-mode starter scaffold generated by gwc start")),
				),
			),
			html.H1(html.Props{}, html.Text("golden-ssr-app")),
			html.P(html.Props{Class: "lede"}, html.Text("Golden output for the SSR scaffold.")),
			html.Div(html.Props{Class: "meta-grid"},
				html.Div(html.Props{Class: "meta-card"},
					html.Span(html.Props{Class: "meta-label"}, html.Text("Author")),
					html.Strong(html.Props{}, html.Text("Golden Test")),
				),
				html.Div(html.Props{Class: "meta-card"},
					html.Span(html.Props{Class: "meta-label"}, html.Text("Version")),
					html.Strong(html.Props{}, html.Text("1.0.0")),
				),
				html.Div(html.Props{Class: "meta-card"},
					html.Span(html.Props{Class: "meta-label"}, html.Text("Preset")),
					html.Strong(html.Props{}, html.Text("SSR App")),
				),
				html.Div(html.Props{Class: "meta-card"},
					html.Span(html.Props{Class: "meta-label"}, html.Text("Module")),
					html.Strong(html.Props{}, html.Text("github.com/example/golden-ssr-app")),
				),
			),
			html.P(html.Props{Class: "lede"}, html.Text("Generated in golden tests.")),
			html.P(html.Props{Class: "meta"}, html.Text("Features: ssr, hydration")),
			html.H2(html.Props{Class: "feature-heading"}, html.Text("Starter capability matrix")),
			html.Div(html.Props{Class: "feature-grid"},
				html.Div(html.Props{Class: "feature-card"},
					html.Span(html.Props{Class: "feature-tag"}, html.Text("SSR")),
					html.P(html.Props{Class: "feature-copy"}, html.Text("Server rendering and hydration expectations are documented in the generated matrix.")),
				),
				html.Div(html.Props{Class: "feature-card"},
					html.Span(html.Props{Class: "feature-tag"}, html.Text("Hydration")),
					html.P(html.Props{Class: "feature-copy"}, html.Text("Client boot and hydration ownership are expected from the first app shell.")),
				),
			),
			html.Div(html.Props{Class: "capability"},
				html.Span(html.Props{Class: "capability-title"}, html.Text("Server Rendering")),
				html.P(html.Props{Class: "capability-copy"}, html.Text("This preset is intended for request-time HTML rendering with launcher-managed release defaults.")),
			),
			html.Div(html.Props{Class: "capability"},
				html.Span(html.Props{Class: "capability-title"}, html.Text("Hydration")),
				html.P(html.Props{Class: "capability-copy"}, html.Text("Hydration-ready app ownership is expected so server output and browser interactivity stay aligned.")),
			),
			html.Div(html.Props{Class: "counter"}, html.Text(fmt.Sprintf("Count: %d", parseCurrentCount))),
			html.Button(html.Props{OnClick: parseIncrement, Class: "button"}, html.Text("Increment")),
		),
	)
}

func main() {
	utils.DisableAllDebug()
	ui.Render(ui.CreateElement(App), "#app")
	utils.WaitForever()
}
