package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const cssThemeFixture = `{
  "colors": {
    "brand-500": "#6366f1",
    "brand-50": "#eef2ff",
    "ink": "#0f172a"
  },
  "fontSizes": { "display": "3rem" },
  "radii": { "pill": "9999px" },
  "spacing": { "7": "1.75rem", "9": "2.25rem" }
}`

func writeCSSThemeFixture(parseT *testing.T) string {
	parseT.Helper()
	parseDir := parseT.TempDir()
	if parseErr := os.WriteFile(filepath.Join(parseDir, "theme.json"), []byte(cssThemeFixture), 0644); parseErr != nil {
		parseT.Fatalf("write fixture: %v", parseErr)
	}
	if parseErr := os.WriteFile(filepath.Join(parseDir, "doc.go"), []byte("package theme\n"), 0644); parseErr != nil {
		parseT.Fatalf("write package file: %v", parseErr)
	}
	return parseDir
}

// TestCollectThemeTokensSortsAcrossScales proves tokens are collected sorted within each
// scale and typed as the matching css/u token type; spacing keys become typed ints.
func TestCollectThemeTokensSortsAcrossScales(parseT *testing.T) {
	parseTokens, parseErr := collectThemeTokens(filepath.Join(writeCSSThemeFixture(parseT), "theme.json"))
	if parseErr != nil {
		parseT.Fatalf("collectThemeTokens: %v", parseErr)
	}
	parseGot := make([]string, len(parseTokens))
	for parseI, parseToken := range parseTokens {
		parseGot[parseI] = parseToken.ident + ":" + parseToken.tokenTyp + ":" + parseToken.value
	}
	// Colors sorted (brand-50 < brand-500 < ink), then fontSizes, radii, spacing (int-sorted).
	parseWant := strings.Join([]string{
		"ColorBrand50:u.ColorToken:brand-50",
		"ColorBrand500:u.ColorToken:brand-500",
		"ColorInk:u.ColorToken:ink",
		"TextDisplay:u.TextScale:display",
		"RadiusPill:u.Radius:pill",
		"Spacing7:u.Spacing:7",
		"Spacing9:u.Spacing:9",
	}, ",")
	if strings.Join(parseGot, ",") != parseWant {
		parseT.Fatalf("expected\n  %s\ngot\n  %s", parseWant, strings.Join(parseGot, ","))
	}
	for _, parseToken := range parseTokens {
		if parseToken.tokenTyp == "u.Spacing" && !parseToken.isInt {
			parseT.Fatalf("spacing token %s must be typed as an int", parseToken.ident)
		}
	}
}

// TestGenerateCSSTokensFileTyped proves the generated source declares typed constants
// (typo-as-compile-error) and is valid Go (format.Source would have errored otherwise).
func TestGenerateCSSTokensFileTyped(parseT *testing.T) {
	parseTokens, _ := collectThemeTokens(filepath.Join(writeCSSThemeFixture(parseT), "theme.json"))
	parseSrc, parseErr := generateCSSTokensFile("theme", parseTokens)
	if parseErr != nil {
		parseT.Fatalf("generate: %v", parseErr)
	}
	// gofmt aligns the const block into columns, so compare with internal runs of
	// whitespace collapsed to a single space.
	parseCollapsed := strings.Join(strings.Fields(parseSrc), " ")
	for _, parseWant := range []string{
		"// Code generated by `gwc css gen`; DO NOT EDIT.",
		"package theme",
		`import "github.com/monstercameron/GoWebComponents/v6/css/u"`,
		`ColorBrand500 u.ColorToken = "brand-500"`,
		`ColorInk u.ColorToken = "ink"`,
		`TextDisplay u.TextScale = "display"`,
		`RadiusPill u.Radius = "pill"`,
		"Spacing7 u.Spacing = 7",
	} {
		if !strings.Contains(parseCollapsed, strings.Join(strings.Fields(parseWant), " ")) {
			parseT.Fatalf("generated source missing %q:\n%s", parseWant, parseSrc)
		}
	}
	// A spacing constant must NOT be a quoted string.
	if strings.Contains(parseSrc, `u.Spacing = "7"`) {
		parseT.Fatalf("spacing token must be an int literal, not a string:\n%s", parseSrc)
	}
}

// TestCSSTokenStaleness proves the CI gate: a matching file is fresh; a drift makes it stale.
func TestCSSTokenStaleness(parseT *testing.T) {
	parseDir := writeCSSThemeFixture(parseT)
	parseTokens, _ := collectThemeTokens(filepath.Join(parseDir, "theme.json"))
	parseSrc, _ := generateCSSTokensFile("theme", parseTokens)

	parseOut := filepath.Join(parseDir, cssGenFile)
	if routesFileMatches(parseOut, parseSrc) {
		parseT.Fatal("absent generated file should not already match")
	}
	_ = os.WriteFile(parseOut, []byte(parseSrc), 0644)
	if !routesFileMatches(parseOut, parseSrc) {
		parseT.Fatal("expected fresh after writing the generated source")
	}
}
