package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// doctorFixReport summarizes what `gwc doctor --fix` changed: structured source edits (reused
// from the check fixer) and any environment/scaffold remediations doctor applied directly.
type doctorFixReport struct {
	Source    checkFixReport `json:"source"`
	Generated []string       `json:"generated"`
}

// applyDoctorFixes auto-applies the deterministic remediations doctor would otherwise only
// print. It (1) applies the structured source edits the check fixer carries — today the
// server-leak build-constraint rewrite — over the working tree, and (2) generates a minimal
// gwc-start.json when one is missing but an app entrypoint is detectable, resolving the
// "Scaffold metadata" warning. Non-deterministic prerequisites (Go not installed, a busy port)
// are still reported by the report itself, since no edit can fix them. Returns what it changed.
func applyDoctorFixes(parseL launcher, parseCwd string, parseJSON bool) (doctorFixReport, error) {
	parseReport := doctorFixReport{Generated: []string{}}
	if strings.TrimSpace(parseCwd) == "" {
		return parseReport, nil
	}

	parseSourceFixes, parseErr := applyCheckFixes(parseL, parseCwd, parseJSON)
	if parseErr != nil {
		return parseReport, parseErr
	}
	parseReport.Source = parseSourceFixes

	parseGenerated, parseGenErr := generateMissingScaffoldMetadata(parseCwd)
	if parseGenErr != nil {
		return parseReport, parseGenErr
	}
	if parseGenerated != "" {
		parseReport.Generated = append(parseReport.Generated, parseGenerated)
	}
	return parseReport, nil
}

// generateMissingScaffoldMetadata writes a minimal gwc-start.json when none exists and an app
// entrypoint is detectable, so `gwc dev`/doctor can resolve scaffold ownership for a hand-built
// app. It returns the relative path written, or "" when nothing was generated (metadata already
// present, or no detectable entrypoint). Existing metadata is never overwritten.
func generateMissingScaffoldMetadata(parseCwd string) (string, error) {
	if _, parsePresent, parseErr := loadScaffoldMetadata(parseCwd); parseErr != nil || parsePresent {
		return "", nil // unreadable metadata is surfaced by the report; present metadata is left alone
	}
	if _, parseAppErr := detectAppPath(parseCwd); parseAppErr != nil {
		return "", nil // nothing to anchor metadata to
	}

	parseMetadata := scaffoldMetadata{
		SchemaVersion: currentScaffoldMetadataSchemaVersion,
		ProjectName:   filepath.Base(parseCwd),
		ModulePath:    readAgenticModulePath(parseCwd),
		Description:   "Generated by `gwc doctor --fix` for a hand-built app.",
	}
	parseContent, parseErr := json.MarshalIndent(parseMetadata, "", "  ")
	if parseErr != nil {
		return "", fmt.Errorf("marshal generated scaffold metadata: %w", parseErr)
	}
	parsePath := filepath.Join(parseCwd, "gwc-start.json")
	if parseErr := os.WriteFile(parsePath, append(parseContent, '\n'), 0644); parseErr != nil {
		return "", fmt.Errorf("write generated scaffold metadata: %w", parseErr)
	}
	return "gwc-start.json", nil
}

// reportDoctorFixes prints the doctor --fix trail for interactive runs (JSON runs carry the
// report in the envelope/report instead).
func reportDoctorFixes(parseReport doctorFixReport, parseJSON bool) {
	if parseJSON {
		return
	}
	for _, parseApplied := range parseReport.Source.Applied {
		fmt.Printf("fix: %s — %s (%s)\n", parseApplied.File, parseApplied.Description, parseApplied.Code)
	}
	for _, parseGenerated := range parseReport.Generated {
		fmt.Printf("fix: generated %s\n", parseGenerated)
	}
	for _, parseManual := range parseReport.Source.Manual {
		fmt.Printf("manual: %d × %s — %s\n", parseManual.Count, parseManual.Code, parseManual.Remediation)
	}
	if len(parseReport.Source.Applied) == 0 && len(parseReport.Generated) == 0 {
		fmt.Println("fix: gofmt applied; no further deterministic remediations needed")
	}
}
