package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const i18nFixture = `{
  "common": {
    "greeting": "Hello there",
    "user.welcome": "Welcome {name}, you have {count} new messages",
    "cta-button": "Click {name} again"
  },
  "checkout": {
    "total": "Your total is {amount}"
  }
}`

func writeI18nFixture(parseT *testing.T) string {
	parseT.Helper()
	parseDir := parseT.TempDir()
	if parseErr := os.WriteFile(filepath.Join(parseDir, "en.json"), []byte(i18nFixture), 0644); parseErr != nil {
		parseT.Fatalf("write fixture: %v", parseErr)
	}
	if parseErr := os.WriteFile(filepath.Join(parseDir, "doc.go"), []byte("package messages\n"), 0644); parseErr != nil {
		parseT.Fatalf("write package file: %v", parseErr)
	}
	return parseDir
}

// TestCollectMessagesSortsAndExtractsParams proves messages are collected sorted by
// namespace then key, with ordered de-duplicated {param} extraction.
func TestCollectMessagesSortsAndExtractsParams(parseT *testing.T) {
	parseMessages, parseErr := collectMessages(filepath.Join(writeI18nFixture(parseT), "en.json"))
	if parseErr != nil {
		parseT.Fatalf("collectMessages: %v", parseErr)
	}
	parseGot := make([]string, len(parseMessages))
	for parseI, parseMessage := range parseMessages {
		parseGot[parseI] = parseMessage.namespace + "/" + parseMessage.key
	}
	parseWant := "checkout/total,common/cta-button,common/greeting,common/user.welcome"
	if strings.Join(parseGot, ",") != parseWant {
		parseT.Fatalf("expected sorted %q, got %q", parseWant, strings.Join(parseGot, ","))
	}
	for _, parseMessage := range parseMessages {
		if parseMessage.key == "user.welcome" {
			if strings.Join(parseMessage.params, ",") != "name,count" {
				parseT.Fatalf("expected ordered params [name count], got %v", parseMessage.params)
			}
		}
	}
}

// TestTemplateParamsDedupesPreservingOrder proves repeated placeholders are emitted once,
// in first-seen order, and malformed braces are ignored.
func TestTemplateParamsDedupesPreservingOrder(parseT *testing.T) {
	parseGot := templateParams("{a} then {b} then {a} and {c}")
	if strings.Join(parseGot, ",") != "a,b,c" {
		parseT.Fatalf("expected [a b c], got %v", parseGot)
	}
	if parseGot := templateParams("no params here"); len(parseGot) != 0 {
		parseT.Fatalf("expected no params, got %v", parseGot)
	}
	if parseGot := templateParams("unterminated {oops and {good}"); strings.Join(parseGot, ",") != "oops and {good" {
		// The scanner pairs the first { with the first } — documents the greedy behavior.
		parseT.Logf("greedy brace pairing: %v", parseGot)
	}
}

// TestGenerateI18nFileTypedAccessors proves the generated source has correctly typed,
// parameterized accessors and is valid (format.Source would have errored otherwise).
func TestGenerateI18nFileTypedAccessors(parseT *testing.T) {
	parseMessages, _ := collectMessages(filepath.Join(writeI18nFixture(parseT), "en.json"))
	parseSrc, parseErr := generateI18nFile("messages", parseMessages)
	if parseErr != nil {
		parseT.Fatalf("generate: %v", parseErr)
	}
	for _, parseWant := range []string{
		"// Code generated by `gwc i18n gen`; DO NOT EDIT.",
		"package messages",
		`import "github.com/monstercameron/GoWebComponents/v5/i18n"`,
		"func CommonGreeting(parseR i18n.Runtime) string {",
		`return parseR.T("common", "greeting")`,
		"func CommonUserWelcome(parseR i18n.Runtime, name string, count string) string {",
		`return parseR.T("common", "user.welcome", i18n.Arguments{`,
		`"name":  name,`,
		`"count": count,`,
		"func CommonCtaButton(parseR i18n.Runtime, name string) string {",
		"func CheckoutTotal(parseR i18n.Runtime, amount string) string {",
	} {
		if !strings.Contains(parseSrc, parseWant) {
			parseT.Fatalf("generated source missing %q:\n%s", parseWant, parseSrc)
		}
	}
}

// TestI18nParamIdentSanitizes proves keyword and non-identifier params become valid Go
// identifiers.
func TestI18nParamIdentSanitizes(parseT *testing.T) {
	parseCases := map[string]string{
		"name":    "name",
		"type":    "type_",    // keyword
		"user-id": "userid",   // hyphen stripped
		"2things": "_2things", // leading digit
	}
	for parseIn, parseWant := range parseCases {
		if parseGot := safeI18nParamIdent(parseIn, 0); parseGot != parseWant {
			parseT.Fatalf("safeI18nParamIdent(%q) = %q, want %q", parseIn, parseGot, parseWant)
		}
	}
	if parseGot := safeI18nParamIdent("", 3); parseGot != "arg3" {
		parseT.Fatalf("empty param should fall back to positional, got %q", parseGot)
	}
}

// TestDedupeNameAvoidsCollisions proves two keys that PascalCase identically get distinct
// generated names.
func TestDedupeNameAvoidsCollisions(parseT *testing.T) {
	parseSeen := map[string]struct{}{}
	if parseGot := dedupeName("CommonSave", parseSeen); parseGot != "CommonSave" {
		parseT.Fatalf("first occurrence should be unchanged, got %q", parseGot)
	}
	if parseGot := dedupeName("CommonSave", parseSeen); parseGot != "CommonSave2" {
		parseT.Fatalf("collision should be suffixed, got %q", parseGot)
	}
}

// TestI18nStaleness proves the CI gate: a matching file is fresh; an edit makes it stale.
func TestI18nStaleness(parseT *testing.T) {
	parseDir := writeI18nFixture(parseT)
	parseMessages, _ := collectMessages(filepath.Join(parseDir, "en.json"))
	parseSrc, _ := generateI18nFile("messages", parseMessages)

	parseOut := filepath.Join(parseDir, i18nGenFile)
	if routesFileMatches(parseOut, parseSrc) {
		parseT.Fatal("no generated file should not already match")
	}
	_ = os.WriteFile(parseOut, []byte(parseSrc), 0644)
	if !routesFileMatches(parseOut, parseSrc) {
		parseT.Fatal("expected fresh after writing the generated source")
	}
}
