package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCollectLintDeprecationRuleIssuesFlagsExportedDeprecatedFunctions(parseT *testing.T) {
	parseRoot := parseT.TempDir()
	parsePath := filepath.Join(parseRoot, "api", "deprecated.go")
	if parseErr := os.MkdirAll(filepath.Dir(parsePath), 0755); parseErr != nil {
		parseT.Fatalf("create api dir: %v", parseErr)
	}
	parseSource := `package api

// OldFunc is kept for compatibility.
//
// Deprecated: Use NewFunc.
func OldFunc() {}

// oldFunc is not a public API.
//
// Deprecated: Use newFunc.
func oldFunc() {}

// OldType is a data shape, not a callable API surface.
//
// Deprecated: Use NewType.
type OldType struct{}

type Widget struct{}

// OldMethod is kept for compatibility.
//
// Deprecated: Use NewMethod.
func (Widget) OldMethod() {}
`
	if parseErr := os.WriteFile(parsePath, []byte(parseSource), 0644); parseErr != nil {
		parseT.Fatalf("write deprecated source: %v", parseErr)
	}

	parseIssues, parseErr := collectLintDeprecationRuleIssues(parseRoot, []string{"./..."})
	if parseErr != nil {
		parseT.Fatalf("collect deprecation rule issues: %v", parseErr)
	}
	if len(parseIssues) != 2 {
		parseT.Fatalf("expected two deprecation issues, got %#v", parseIssues)
	}
	parseJoined := parseIssues[0].Message + "\n" + parseIssues[1].Message
	for _, parseNeedle := range []string{"OldFunc", "Widget.OldMethod", "deprecation.Warn"} {
		if !strings.Contains(parseJoined, parseNeedle) {
			parseT.Fatalf("expected deprecation issues to contain %q, got:\n%s", parseNeedle, parseJoined)
		}
	}
	for _, parseIssue := range parseIssues {
		if parseIssue.Linter != lintDeprecationRuleLinter || parseIssue.Severity != "error" || parseIssue.Path != "api/deprecated.go" {
			parseT.Fatalf("unexpected issue metadata %#v", parseIssue)
		}
		if parseIssue.SourceLine == "" {
			parseT.Fatalf("expected source line on issue %#v", parseIssue)
		}
	}
}

func TestCollectLintDeprecationRuleIssuesAcceptsWarnCalls(parseT *testing.T) {
	parseRoot := parseT.TempDir()
	parsePath := filepath.Join(parseRoot, "api", "deprecated.go")
	if parseErr := os.MkdirAll(filepath.Dir(parsePath), 0755); parseErr != nil {
		parseT.Fatalf("create api dir: %v", parseErr)
	}
	parseSource := `package api

import gwcdep "github.com/monstercameron/GoWebComponents/v4/deprecation"

// OldFunc is kept for compatibility.
//
// Deprecated: Use NewFunc.
func OldFunc() {
	gwcdep.Warn("api.OldFunc", "api.NewFunc")
}

type Widget struct{}

// OldMethod is kept for compatibility.
//
// Deprecated: Use NewMethod.
func (*Widget) OldMethod() {
	gwcdep.Warn("api.Widget.OldMethod", "api.Widget.NewMethod")
}
`
	if parseErr := os.WriteFile(parsePath, []byte(parseSource), 0644); parseErr != nil {
		parseT.Fatalf("write deprecated source: %v", parseErr)
	}

	parseIssues, parseErr := collectLintDeprecationRuleIssues(parseRoot, []string{"./..."})
	if parseErr != nil {
		parseT.Fatalf("collect deprecation rule issues: %v", parseErr)
	}
	if len(parseIssues) != 0 {
		parseT.Fatalf("expected deprecated APIs with warnings to pass, got %#v", parseIssues)
	}
}

func TestCollectLintDeprecationRuleIssuesSkipsGeneratedSource(parseT *testing.T) {
	parseRoot := parseT.TempDir()
	parsePath := filepath.Join(parseRoot, "proto", "api.pb.go")
	if parseErr := os.MkdirAll(filepath.Dir(parsePath), 0755); parseErr != nil {
		parseT.Fatalf("create proto dir: %v", parseErr)
	}
	parseSource := `// Code generated by protoc-gen-go. DO NOT EDIT.
package proto

// Descriptor is generated compatibility code.
//
// Deprecated: Use ProtoReflect.Descriptor instead.
func Descriptor() {}
`
	if parseErr := os.WriteFile(parsePath, []byte(parseSource), 0644); parseErr != nil {
		parseT.Fatalf("write generated source: %v", parseErr)
	}

	parseIssues, parseErr := collectLintDeprecationRuleIssues(parseRoot, []string{"./..."})
	if parseErr != nil {
		parseT.Fatalf("collect generated deprecation rule issues: %v", parseErr)
	}
	if len(parseIssues) != 0 {
		parseT.Fatalf("expected generated source to be skipped, got %#v", parseIssues)
	}
}

func TestBuildLintSummaryIncludesDeprecationRuleIssues(parseT *testing.T) {
	parseRoot := parseT.TempDir()
	parsePath := filepath.Join(parseRoot, "api.go")
	parseSource := `package app

// OldFunc is kept for compatibility.
//
// Deprecated: Use NewFunc.
func OldFunc() {}
`
	if parseErr := os.WriteFile(parsePath, []byte(parseSource), 0644); parseErr != nil {
		parseT.Fatalf("write source: %v", parseErr)
	}

	parseOriginalResolveLintExecutable := resolveLintExecutable
	parseOriginalRunLintProcess := runLintProcess
	parseT.Cleanup(func() {
		resolveLintExecutable = parseOriginalResolveLintExecutable
		runLintProcess = parseOriginalRunLintProcess
	})
	resolveLintExecutable = func(parseToolPath string) (string, error) {
		return filepath.Join(parseRoot, "bin", "golangci-lint"), nil
	}
	runLintProcess = func(parseCommand string, parseArgs []string, parseWorkingDir string, parseEnv []string) (lintProcessResult, error) {
		if len(parseArgs) > 0 && parseArgs[0] == "version" {
			return lintProcessResult{stdout: "2.4.0"}, nil
		}
		if len(parseArgs) == 2 && parseArgs[0] == "config" && parseArgs[1] == "path" {
			return lintProcessResult{}, nil
		}
		return lintProcessResult{stdout: `{"Issues":[]}`}, nil
	}

	parseSummary, isParseIssuesFound, parseErr := buildLintSummary(lintConfig{
		rootPath: parseRoot,
		toolPath: "golangci-lint",
		paths:    []string{"./..."},
	})
	if parseErr != nil {
		parseT.Fatalf("build lint summary: %v", parseErr)
	}
	if !isParseIssuesFound || parseSummary.OK || parseSummary.IssueCount != 1 {
		parseT.Fatalf("expected one deprecation lint failure, found=%v summary=%#v", isParseIssuesFound, parseSummary)
	}
	if parseSummary.LinterCounts[lintDeprecationRuleLinter] != 1 {
		parseT.Fatalf("expected deprecation linter count, got %#v", parseSummary.LinterCounts)
	}
}
