package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// negotiateLLMSContentType picks the response Content-Type for the llms docs from the Accept
// header: text/markdown when the client asks for it, text/plain otherwise — so an agent can
// fetch the docs over HTTP with the content type it wants, not only as a file on disk.
func negotiateLLMSContentType(parseAccept string) string {
	if strings.Contains(parseAccept, "text/markdown") || strings.Contains(parseAccept, "text/x-markdown") {
		return "text/markdown; charset=utf-8"
	}
	return "text/plain; charset=utf-8"
}

// LLMSHandler serves the given llms content over HTTP with Accept-header content
// negotiation (the file-only `gwc llms` output, made fetchable for agents).
func LLMSHandler(parseContent string) http.HandlerFunc {
	return func(parseW http.ResponseWriter, parseR *http.Request) {
		parseW.Header().Set("Content-Type", negotiateLLMSContentType(parseR.Header.Get("Accept")))
		_, _ = io.WriteString(parseW, parseContent)
	}
}

// runLLMsCommand routes the AI-native docs generation command.
var runLLMsCommand = func(parseL launcher, parseArgs []string) error {
	return parseL.runLLMs(parseArgs)
}

const (
	llmsIndexFile = "llms.txt"
	llmsFullFile  = "llms-full.txt"
	manualRelDir  = "docs/REFERENCE_MANUAL"
)

// llmsDoc is one reference-manual document discovered for the llms index.
type llmsDoc struct {
	relPath string // repo-relative, slash-separated
	title   string // first H1 heading
	summary string // first prose line under the heading
	body    string // full markdown
}

// runLLMs parses flags and either writes or staleness-checks the llms.txt /
// llms-full.txt machine-readable docs.
func (parseL launcher) runLLMs(parseArgs []string) error {
	parseFlags := flag.NewFlagSet("llms", flag.ContinueOnError)
	parseFlags.SetOutput(os.Stdout)
	parseRoot := parseFlags.String("root", "", "Project root; defaults to the current working directory")
	parseCheck := parseFlags.Bool("check", false, "Do not write; exit non-zero if llms.txt/llms-full.txt are stale (CI gate)")
	if parseErr := parseFlags.Parse(parseArgs); parseErr != nil {
		if errors.Is(parseErr, flag.ErrHelp) {
			return nil
		}
		return parseErr
	}

	parseRootPath := strings.TrimSpace(*parseRoot)
	if parseRootPath == "" {
		parseCWD, parseErr := os.Getwd()
		if parseErr != nil {
			return fmt.Errorf("resolve llms root from cwd: %w", parseErr)
		}
		parseRootPath = parseCWD
	}
	parseAbs, parseErr := filepath.Abs(parseRootPath)
	if parseErr != nil {
		return fmt.Errorf("resolve llms root: %w", parseErr)
	}

	parseIndex, parseFull, parseErr := buildLLMS(parseAbs)
	if parseErr != nil {
		return parseErr
	}

	if *parseCheck {
		parseStale := llmsStaleFiles(parseAbs, parseIndex, parseFull)
		if len(parseStale) > 0 {
			fmt.Printf("GWC llms: STALE — %s out of date; run `gwc llms` and commit\n", strings.Join(parseStale, ", "))
			return fmt.Errorf("llms docs are stale: %s", strings.Join(parseStale, ", "))
		}
		fmt.Println("GWC llms: up to date")
		return nil
	}

	if parseErr := os.WriteFile(filepath.Join(parseAbs, llmsIndexFile), []byte(parseIndex), 0644); parseErr != nil {
		return fmt.Errorf("write %s: %w", llmsIndexFile, parseErr)
	}
	if parseErr := os.WriteFile(filepath.Join(parseAbs, llmsFullFile), []byte(parseFull), 0644); parseErr != nil {
		return fmt.Errorf("write %s: %w", llmsFullFile, parseErr)
	}
	fmt.Printf("GWC llms: wrote %s + %s\n", llmsIndexFile, llmsFullFile)
	return nil
}

// buildLLMS generates the llms.txt index and the llms-full.txt concatenation for
// the project at rootPath, following the llms.txt convention.
func buildLLMS(parseRootPath string) (parseIndex string, parseFull string, parseErr error) {
	parseTitle, parseSummary := llmsProjectHeader(parseRootPath)
	parseDocs, parseErr := collectManualDocs(parseRootPath)
	if parseErr != nil {
		return "", "", parseErr
	}

	var parseIndexBuilder strings.Builder
	fmt.Fprintf(&parseIndexBuilder, "# %s\n\n> %s\n\n", parseTitle, parseSummary)
	parseIndexBuilder.WriteString("## Reference Manual\n\n")
	for _, parseDoc := range parseDocs {
		fmt.Fprintf(&parseIndexBuilder, "- [%s](%s)", parseDoc.title, parseDoc.relPath)
		if parseDoc.summary != "" {
			fmt.Fprintf(&parseIndexBuilder, ": %s", parseDoc.summary)
		}
		parseIndexBuilder.WriteString("\n")
	}
	parseIndexBuilder.WriteString("\n## Project\n\n")
	parseIndexBuilder.WriteString("- [README](README.md): project overview and quick start\n")
	parseIndexBuilder.WriteString("- [CHANGELOG](CHANGELOG.md): release history\n")
	parseIndexBuilder.WriteString("- [Full docs](llms-full.txt): every reference-manual chapter concatenated for full-context ingestion\n")

	var parseFullBuilder strings.Builder
	fmt.Fprintf(&parseFullBuilder, "# %s — full documentation\n\n> %s\n\n", parseTitle, parseSummary)
	parseFullBuilder.WriteString("Generated by `gwc llms`. Source of truth: " + manualRelDir + "/*.md\n")
	for _, parseDoc := range parseDocs {
		fmt.Fprintf(&parseFullBuilder, "\n\n---\n\n<!-- source: %s -->\n\n", parseDoc.relPath)
		parseFullBuilder.WriteString(strings.TrimRight(parseDoc.body, "\n"))
		parseFullBuilder.WriteString("\n")
	}

	return parseIndexBuilder.String(), parseFullBuilder.String(), nil
}

// collectManualDocs reads docs/REFERENCE_MANUAL/*.md (excluding its README index),
// ordered by filename, extracting each doc's H1 title and first prose summary line.
func collectManualDocs(parseRootPath string) ([]llmsDoc, error) {
	parseDir := filepath.Join(parseRootPath, filepath.FromSlash(manualRelDir))
	parseEntries, parseErr := os.ReadDir(parseDir)
	if parseErr != nil {
		return nil, fmt.Errorf("read manual dir %s: %w", parseDir, parseErr)
	}
	parseNames := make([]string, 0, len(parseEntries))
	for _, parseEntry := range parseEntries {
		if parseEntry.IsDir() || !strings.HasSuffix(parseEntry.Name(), ".md") {
			continue
		}
		if strings.EqualFold(parseEntry.Name(), "README.md") {
			continue
		}
		parseNames = append(parseNames, parseEntry.Name())
	}
	sort.Strings(parseNames)

	parseDocs := make([]llmsDoc, 0, len(parseNames))
	for _, parseName := range parseNames {
		parseData, parseReadErr := os.ReadFile(filepath.Join(parseDir, parseName))
		if parseReadErr != nil {
			return nil, parseReadErr
		}
		parseBody := string(parseData)
		parseTitle, parseSummary := extractTitleAndSummary(parseBody, parseName)
		parseDocs = append(parseDocs, llmsDoc{
			relPath: manualRelDir + "/" + parseName,
			title:   parseTitle,
			summary: parseSummary,
			body:    parseBody,
		})
	}
	return parseDocs, nil
}

// extractTitleAndSummary returns the first H1 heading (sans "# ") and the first
// non-empty prose line beneath it, falling back to the filename for the title.
func extractTitleAndSummary(parseBody string, parseFallbackName string) (string, string) {
	parseTitle := strings.TrimSuffix(parseFallbackName, ".md")
	parseSummary := ""
	parseSawTitle := false
	for parseLine := range strings.SplitSeq(parseBody, "\n") {
		parseTrimmed := strings.TrimSpace(parseLine)
		if !parseSawTitle {
			if parseRest, parseIsTitle := strings.CutPrefix(parseTrimmed, "# "); parseIsTitle {
				parseTitle = strings.TrimSpace(parseRest)
				parseSawTitle = true
			}
			continue
		}
		if parseTrimmed == "" || isLLMSNonProse(parseTrimmed) {
			continue
		}
		parseSummary = llmsTruncate(parseTrimmed, 160)
		break
	}
	return parseTitle, parseSummary
}

// isLLMSNonProse reports whether a line is markup we should skip when looking for a
// one-line prose summary (headings, lists, tables, blockquotes, code fences, html).
func isLLMSNonProse(parseLine string) bool {
	switch {
	case strings.HasPrefix(parseLine, "#"),
		strings.HasPrefix(parseLine, "-"),
		strings.HasPrefix(parseLine, "*"),
		strings.HasPrefix(parseLine, ">"),
		strings.HasPrefix(parseLine, "|"),
		strings.HasPrefix(parseLine, "```"),
		strings.HasPrefix(parseLine, "<"),
		strings.HasPrefix(parseLine, "["), // markdown links / CI badges
		strings.HasPrefix(parseLine, "!["):
		return true
	default:
		return false
	}
}

// llmsProjectHeader returns the project title and one-line summary from README.md,
// with stable fallbacks so generation is deterministic even without a README.
func llmsProjectHeader(parseRootPath string) (string, string) {
	parseTitle := "GoWebComponents"
	parseSummary := "A Go + WebAssembly UI framework: React-style components and hooks, fine-grained signals, typed CSS, routing, shared state, SSR/hydration, and batteries-included tooling — one language, no npm."
	parseData, parseErr := os.ReadFile(filepath.Join(parseRootPath, "README.md"))
	if parseErr != nil {
		return parseTitle, parseSummary
	}
	parseDocTitle, parseDocSummary := extractTitleAndSummary(string(parseData), parseTitle)
	if parseDocTitle != "" {
		parseTitle = parseDocTitle
	}
	if parseDocSummary != "" {
		parseSummary = parseDocSummary
	}
	return parseTitle, parseSummary
}

// llmsStaleFiles returns the names of the generated files whose on-disk content
// differs from the freshly generated content (or are missing).
func llmsStaleFiles(parseRootPath, parseIndex, parseFull string) []string {
	var parseStale []string
	if !llmsFileMatches(filepath.Join(parseRootPath, llmsIndexFile), parseIndex) {
		parseStale = append(parseStale, llmsIndexFile)
	}
	if !llmsFileMatches(filepath.Join(parseRootPath, llmsFullFile), parseFull) {
		parseStale = append(parseStale, llmsFullFile)
	}
	return parseStale
}

// llmsFileMatches reports whether the file at path exists and equals want.
func llmsFileMatches(parsePath, parseWant string) bool {
	parseData, parseErr := os.ReadFile(parsePath)
	if parseErr != nil {
		return false
	}
	return string(parseData) == parseWant
}

// llmsTruncate shortens s to at most max runes, appending an ellipsis when cut.
func llmsTruncate(parseS string, parseMax int) string {
	parseRunes := []rune(parseS)
	if len(parseRunes) <= parseMax {
		return parseS
	}
	return strings.TrimSpace(string(parseRunes[:parseMax])) + "…"
}
