package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const routesFixture = `package myapp

import "github.com/monstercameron/GoWebComponents/v5/router"

var (
	HomeRoute = router.MustDefineRoute("/")
	UserRoute = router.MustDefineRoute("/users/:id")
	PostRoute = router.DefineRouteMustNot("/ignored") // not a route ctor
	unexported = router.MustDefineRoute("/secret")
)

var DeepRoute = router.MustDefineRoute("/orgs/:org/repos/:repo")
`

func writeRoutesFixture(parseT *testing.T) string {
	parseT.Helper()
	parseDir := parseT.TempDir()
	if parseErr := os.WriteFile(filepath.Join(parseDir, "routes.go"), []byte(routesFixture), 0644); parseErr != nil {
		parseT.Fatalf("write fixture: %v", parseErr)
	}
	// A test file + the generated file must both be ignored by the scanner.
	_ = os.WriteFile(filepath.Join(parseDir, "routes_test.go"), []byte("package myapp\n"), 0644)
	_ = os.WriteFile(filepath.Join(parseDir, routesGenFile), []byte("package myapp\n"), 0644)
	return parseDir
}

// TestCollectRoutesFindsExportedContracts proves only exported MustDefineRoute/
// DefineRoute contracts are collected (skipping unexported, non-ctor calls, tests,
// and the generated file), sorted by name.
func TestCollectRoutesFindsExportedContracts(parseT *testing.T) {
	parsePkg, parseRoutes, parseErr := collectRoutes(writeRoutesFixture(parseT))
	if parseErr != nil {
		parseT.Fatalf("collectRoutes: %v", parseErr)
	}
	if parsePkg != "myapp" {
		parseT.Fatalf("pkg name: got %q", parsePkg)
	}
	parseNames := make([]string, len(parseRoutes))
	for parseI, parseRoute := range parseRoutes {
		parseNames[parseI] = parseRoute.varName
	}
	parseGot := strings.Join(parseNames, ",")
	if parseGot != "DeepRoute,HomeRoute,UserRoute" {
		parseT.Fatalf("expected sorted [DeepRoute HomeRoute UserRoute], got %q", parseGot)
	}
}

// TestPatternParamsOrdered proves :param extraction preserves order.
func TestPatternParamsOrdered(parseT *testing.T) {
	parseGot := patternParams("/orgs/:org/repos/:repo/issues/:num")
	parseWant := []string{"org", "repo", "num"}
	if strings.Join(parseGot, ",") != strings.Join(parseWant, ",") {
		parseT.Fatalf("expected %v, got %v", parseWant, parseGot)
	}
	if len(patternParams("/static/path")) != 0 {
		parseT.Fatal("expected no params for a static path")
	}
}

// TestGenerateRoutesFileTypedConstructors proves the generated source has correctly
// typed constructors and is valid (format.Source would have errored otherwise).
func TestGenerateRoutesFileTypedConstructors(parseT *testing.T) {
	_, parseRoutes, _ := collectRoutes(writeRoutesFixture(parseT))
	parseSrc, parseErr := generateRoutesFile("myapp", parseRoutes)
	if parseErr != nil {
		parseT.Fatalf("generate: %v", parseErr)
	}
	for _, parseWant := range []string{
		"// Code generated by `gwc routes gen`; DO NOT EDIT.",
		"package myapp",
		`import "net/url"`,
		"func LinkHome() string {",
		"return HomeRoute.MustHref(nil, nil)",
		"func LinkHomeWithQuery(query url.Values) string {",
		"return HomeRoute.MustHref(nil, query)",
		"func LinkUser(id string) string {",
		`UserRoute.MustHref(map[string]string{"id": id}, nil)`,
		"func LinkUserWithQuery(id string, query url.Values) string {",
		`UserRoute.MustHref(map[string]string{"id": id}, query)`,
		"func LinkDeep(org string, repo string) string {",
		`map[string]string{"org": org, "repo": repo}`,
	} {
		if !strings.Contains(parseSrc, parseWant) {
			parseT.Fatalf("generated source missing %q:\n%s", parseWant, parseSrc)
		}
	}
}

// TestSafeRouteParamIdent proves keyword, hyphenated, and empty params become valid
// Go identifiers.
func TestSafeRouteParamIdent(parseT *testing.T) {
	parseCases := map[string]string{
		"id":      "id",
		"type":    "type_",   // keyword
		"user-id": "user_id", // hyphen sanitized
		"func":    "func_",   // keyword
	}
	for parseIn, parseWant := range parseCases {
		if parseGot := safeRouteParamIdent(parseIn, 0); parseGot != parseWant {
			parseT.Fatalf("safeRouteParamIdent(%q) = %q, want %q", parseIn, parseGot, parseWant)
		}
	}
	if parseGot := safeRouteParamIdent("", 2); parseGot != "arg2" {
		parseT.Fatalf("empty param should fall back to positional, got %q", parseGot)
	}
}

// TestRoutesStaleness proves the CI gate: a matching file is fresh; an edit makes it
// stale.
func TestRoutesStaleness(parseT *testing.T) {
	parseDir := writeRoutesFixture(parseT)
	_, parseRoutes, _ := collectRoutes(parseDir)
	parseSrc, _ := generateRoutesFile("myapp", parseRoutes)

	parseOut := filepath.Join(parseDir, routesGenFile)
	if routesFileMatches(parseOut, parseSrc) {
		parseT.Fatal("placeholder generated file should not already match")
	}
	_ = os.WriteFile(parseOut, []byte(parseSrc), 0644)
	if !routesFileMatches(parseOut, parseSrc) {
		parseT.Fatal("expected fresh after writing the generated source")
	}
}
