package main

import (
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

// runBundleCommand routes `gwc bundle` — scaffolding a single-binary, whole-stack server.
var runBundleCommand = func(parseL launcher, parseArgs []string) error {
	return parseL.runBundle(parseArgs)
}

const bundleServerFile = "cmd/server/main.go"

// runBundle parses `gwc bundle [-assets dist] [-addr :8080] [-out cmd/server/main.go]` and
// writes a Go server main that embeds the built client assets and serves them plus the app's
// //gwc:server functions from one binary (via wholestack) — the FC5 "one command, one binary"
// deployment story.
func (parseL launcher) runBundle(parseArgs []string) error {
	parseFlags := flag.NewFlagSet("bundle", flag.ContinueOnError)
	parseFlags.SetOutput(os.Stdout)
	parseAssets := parseFlags.String("assets", "dist", "Directory of built client assets to embed")
	parseAddr := parseFlags.String("addr", ":8080", "Listen address for the generated server")
	parseOut := parseFlags.String("out", bundleServerFile, "Output path for the generated server main")
	if parseErr := parseFlags.Parse(parseArgs); parseErr != nil {
		if errors.Is(parseErr, flag.ErrHelp) {
			return nil
		}
		return parseErr
	}

	parseSource, parseErr := generateSingleBinaryServer(*parseAssets, *parseAddr)
	if parseErr != nil {
		return parseErr
	}
	if parseErr := os.MkdirAll(filepath.Dir(*parseOut), 0755); parseErr != nil {
		return fmt.Errorf("create %s: %w", filepath.Dir(*parseOut), parseErr)
	}
	if parseErr := os.WriteFile(*parseOut, []byte(parseSource), 0644); parseErr != nil {
		return fmt.Errorf("write %s: %w", *parseOut, parseErr)
	}
	fmt.Printf("GWC bundle: wrote %s — build it with `go build -o app ./%s` for a single whole-stack binary\n", *parseOut, filepath.ToSlash(filepath.Dir(*parseOut)))
	return nil
}

// generateSingleBinaryServer renders a Go server main that go:embeds the assets directory and
// serves it via wholestack.Handler. The result is gofmt-clean and compiles as-is (static
// serving); the developer uncomments the RegisterServerFns line to wire their server
// functions.
func generateSingleBinaryServer(parseAssetsDir, parseAddr string) (string, error) {
	parseAssetsDir = strings.Trim(filepath.ToSlash(parseAssetsDir), "/")
	if parseAssetsDir == "" {
		parseAssetsDir = "dist"
	}

	var parseBuilder strings.Builder
	parseBuilder.WriteString("// Code generated by `gwc bundle`; edit to wire your server functions.\n\n")
	parseBuilder.WriteString("package main\n\n")
	parseBuilder.WriteString("import (\n\t\"embed\"\n\t\"io/fs\"\n\t\"log\"\n\t\"net/http\"\n\n\t\"github.com/monstercameron/GoWebComponents/v6/wholestack\"\n)\n\n")
	fmt.Fprintf(&parseBuilder, "//go:embed all:%s\n", parseAssetsDir)
	parseBuilder.WriteString("var assets embed.FS\n\n")
	parseBuilder.WriteString("func main() {\n")
	fmt.Fprintf(&parseBuilder, "\tsub, err := fs.Sub(assets, %q)\n", parseAssetsDir)
	parseBuilder.WriteString("\tif err != nil {\n\t\tlog.Fatal(err)\n\t}\n")
	parseBuilder.WriteString("\thandler := wholestack.Handler(wholestack.Options{\n")
	parseBuilder.WriteString("\t\tAssets: sub,\n")
	parseBuilder.WriteString("\t\t// RegisterServerFns: yourpkg.RegisterServerFunctions, // wire your //gwc:server functions\n")
	parseBuilder.WriteString("\t})\n")
	fmt.Fprintf(&parseBuilder, "\taddr := %q\n", parseAddr)
	parseBuilder.WriteString("\tlog.Printf(\"single-binary app serving on %s\", addr)\n")
	parseBuilder.WriteString("\tlog.Fatal(http.ListenAndServe(addr, handler))\n")
	parseBuilder.WriteString("}\n")

	parseFormatted, parseErr := format.Source([]byte(parseBuilder.String()))
	if parseErr != nil {
		return "", fmt.Errorf("format single-binary server: %w", parseErr)
	}
	return string(parseFormatted), nil
}
