package main

import (
	"fmt"
	"path/filepath"
	"strings"
)

func renderScaffoldExtraFiles(parseSelection startSelection) map[string][]byte {
	parseFiles := map[string][]byte{
		"FEATURE_MATRIX.md":        []byte(renderScaffoldFeatureMatrix(parseSelection)),
		"starter_test.go":          []byte(renderScaffoldFeatureBaselineTest(parseSelection)),
		".github/workflows/ci.yml": []byte(renderScaffoldGitHubActionsWorkflow(parseSelection)),
	}
	if scaffoldHasFeature(startSelectionFeatures(parseSelection), "browser-tests") {
		parseFiles["test/playwrightgo/README.md"] = []byte(renderScaffoldBrowserTestREADME(parseSelection))
		parseFiles["test/playwrightgo/smoke_test.go"] = []byte(renderScaffoldBrowserSmokeTest(parseSelection))
	}
	return parseFiles
}

func renderScaffoldMain(parseSelection startSelection, parseRepoModulePath string) string {
	parseNormalizedFeatures := startSelectionFeatures(parseSelection)
	parseFeatureList := strings.Join(parseNormalizedFeatures, ", ")
	if parseFeatureList == "" {
		parseFeatureList = "core-only"
	}
	parseFeatureCards := renderScaffoldFeatureCards(parseNormalizedFeatures)
	parseCapabilityState := renderScaffoldCapabilityState(parseNormalizedFeatures)
	parseCapabilityWidgets := renderScaffoldCapabilityWidgets(parseNormalizedFeatures)
	return fmt.Sprintf(`//go:build js && wasm
// +build js,wasm

package main

import (
	"fmt"

	%q
	%q
	%q
)

func App() ui.Node {
	parseCount := ui.UseState(0)
	parseCurrentCount := parseCount.Get()

	parseIncrement := ui.UseEvent(func() {
		parseCount.Update(func(previous int) int { return previous + 1 })
	})

%s

	return html.Div(html.Props{Class: "shell"},
		html.Div(html.Props{Class: "panel"},
			html.Div(html.Props{Class: "brand-row"},
				html.Div(html.Props{Class: "brand-mark"}, html.Text("GWC")),
				html.Div(html.Props{},
					html.P(html.Props{Class: "eyebrow"}, html.Text("GoWebComponents Starter")),
					html.P(html.Props{Class: "brand-copy"}, html.Text("Dark-mode starter scaffold generated by gwc start")),
				),
			),
			html.H1(html.Props{}, html.Text(%q)),
			html.P(html.Props{Class: "lede"}, html.Text(%q)),
			html.Div(html.Props{Class: "meta-grid"},
				html.Div(html.Props{Class: "meta-card"},
					html.Span(html.Props{Class: "meta-label"}, html.Text("Author")),
					html.Strong(html.Props{}, html.Text(%q)),
				),
				html.Div(html.Props{Class: "meta-card"},
					html.Span(html.Props{Class: "meta-label"}, html.Text("Version")),
					html.Strong(html.Props{}, html.Text(%q)),
				),
				html.Div(html.Props{Class: "meta-card"},
					html.Span(html.Props{Class: "meta-label"}, html.Text("Preset")),
					html.Strong(html.Props{}, html.Text(%q)),
				),
				html.Div(html.Props{Class: "meta-card"},
					html.Span(html.Props{Class: "meta-label"}, html.Text("Module")),
					html.Strong(html.Props{}, html.Text(%q)),
				),
			),
			html.P(html.Props{Class: "lede"}, html.Text(%q)),
			html.P(html.Props{Class: "meta"}, html.Text(%q)),
			html.H2(html.Props{Class: "feature-heading"}, html.Text("Starter capability matrix")),
			html.Div(html.Props{Class: "feature-grid"},
%s
			),
%s
			html.Div(html.Props{Class: "counter"}, html.Text(fmt.Sprintf("Count: %%d", parseCurrentCount))),
			html.Button(html.Props{OnClick: parseIncrement, Class: "button"}, html.Text("Increment")),
		),
	)
}

func main() {
	utils.DisableAllDebug()
	ui.Render(ui.CreateElement(App), "#app")
	utils.WaitForever()
}
`, parseRepoModulePath+"/html", parseRepoModulePath+"/ui", parseRepoModulePath+"/utils", parseCapabilityState, parseSelection.ProjectName, parseSelection.Description, parseSelection.Author, parseSelection.Version, parseSelection.Preset.Name, parseSelection.ModulePath, parseSelection.Preset.Description, "Features: "+parseFeatureList, parseFeatureCards, parseCapabilityWidgets)
}

func renderScaffoldHTML(parseSelection startSelection) string {
	parseTemplate := `<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>__GWC_PROJECT_TITLE__</title>
	<script src="./wasm_exec.js"></script>
	<style>
		:root { color-scheme: dark; }
		* { box-sizing: border-box; }
		body {
			margin: 0;
			font-family: "Segoe UI", sans-serif;
			background:
				radial-gradient(circle at top, rgba(97, 218, 251, 0.18), transparent 32%),
				linear-gradient(160deg, #050816 0%, #0d1326 48%, #111c2b 100%);
			color: #eef4ff;
		}
		.shell {
			min-height: 100vh;
			display: flex;
			align-items: center;
			justify-content: center;
			padding: 24px;
		}
		.panel {
			width: min(560px, 100%);
			background: rgba(8, 13, 25, 0.84);
			border: 1px solid rgba(97, 218, 251, 0.14);
			border-radius: 24px;
			padding: 32px;
			box-shadow: 0 28px 90px rgba(0, 0, 0, 0.42);
			backdrop-filter: blur(18px);
		}
		.brand-row {
			display: flex;
			align-items: center;
			gap: 14px;
			margin-bottom: 18px;
		}
		.brand-mark {
			display: inline-flex;
			align-items: center;
			justify-content: center;
			width: 48px;
			height: 48px;
			border-radius: 14px;
			background: linear-gradient(135deg, #61dafb 0%, #35b4d8 100%);
			color: #03131d;
			font-weight: 800;
			letter-spacing: 0.08em;
		}
		.brand-copy {
			margin: 4px 0 0;
			font-size: 0.9rem;
			color: #8ca2c7;
		}
		.eyebrow {
			margin: 0 0 12px;
			text-transform: uppercase;
			letter-spacing: 0.18em;
			font-size: 12px;
			color: #61dafb;
		}
		h1 {
			margin: 0 0 12px;
			font-size: clamp(2rem, 6vw, 3.2rem);
			line-height: 1;
			color: #f7fbff;
		}
		.lede {
			margin: 0 0 12px;
			font-size: 1.05rem;
			color: #d5e0f5;
		}
		.meta {
			margin: 0 0 24px;
			font-size: 0.95rem;
			color: #8ca2c7;
		}
		.feature-heading {
			margin: 0 0 10px;
			font-size: 1rem;
			text-transform: uppercase;
			letter-spacing: 0.12em;
			color: #61dafb;
		}
		.feature-grid {
			display: grid;
			grid-template-columns: repeat(2, minmax(0, 1fr));
			gap: 10px;
			margin: 0 0 20px;
		}
		.feature-card {
			padding: 12px;
			border-radius: 14px;
			background: rgba(97, 218, 251, 0.06);
			border: 1px solid rgba(97, 218, 251, 0.14);
		}
		.feature-tag {
			display: block;
			font-size: 0.76rem;
			font-weight: 700;
			text-transform: uppercase;
			letter-spacing: 0.08em;
			color: #b9f0ff;
			margin-bottom: 6px;
		}
		.feature-copy {
			margin: 0;
			font-size: 0.84rem;
			color: #c6d7f2;
			line-height: 1.4;
		}
		.capability {
			margin: 0 0 14px;
			padding: 12px;
			border-radius: 14px;
			border: 1px solid rgba(97, 218, 251, 0.18);
			background: rgba(5, 15, 33, 0.66);
		}
		.capability-title {
			display: block;
			font-size: 0.74rem;
			font-weight: 700;
			text-transform: uppercase;
			letter-spacing: 0.12em;
			color: #9be8ff;
			margin-bottom: 6px;
		}
		.capability-copy {
			margin: 0 0 10px;
			font-size: 0.9rem;
			color: #dce8ff;
		}
		.capability-actions {
			display: flex;
			flex-wrap: wrap;
			gap: 8px;
		}
		.capability-button {
			border: 1px solid rgba(97, 218, 251, 0.28);
			border-radius: 999px;
			padding: 8px 14px;
			background: rgba(97, 218, 251, 0.1);
			color: #d8f6ff;
			font: inherit;
			font-size: 0.84rem;
			font-weight: 600;
			cursor: pointer;
		}
		.capability-input {
			width: 100%;
			margin-bottom: 10px;
			padding: 10px 12px;
			border-radius: 10px;
			border: 1px solid rgba(97, 218, 251, 0.22);
			background: rgba(3, 10, 26, 0.92);
			color: #f1f7ff;
			font: inherit;
		}
		.meta-grid {
			display: grid;
			grid-template-columns: repeat(2, minmax(0, 1fr));
			gap: 12px;
			margin: 0 0 20px;
		}
		.meta-card {
			padding: 14px 16px;
			border-radius: 16px;
			background: rgba(97, 218, 251, 0.06);
			border: 1px solid rgba(97, 218, 251, 0.12);
		}
		.meta-label {
			display: block;
			font-size: 0.72rem;
			text-transform: uppercase;
			letter-spacing: 0.14em;
			color: #8ca2c7;
			margin-bottom: 6px;
		}
		strong {
			color: #f7fbff;
		}
		.counter {
			font-size: 2rem;
			font-weight: 700;
			margin-bottom: 20px;
			color: #f7fbff;
		}
		.button {
			border: 0;
			border-radius: 999px;
			padding: 14px 22px;
			background: linear-gradient(135deg, #61dafb 0%, #35b4d8 100%);
			color: #03131d;
			font: inherit;
			font-weight: 700;
			cursor: pointer;
			box-shadow: 0 14px 30px rgba(53, 180, 216, 0.28);
		}
		.button:hover {
			filter: brightness(1.06);
		}
		@media (max-width: 640px) {
			.meta-grid {
				grid-template-columns: 1fr;
			}
			.feature-grid {
				grid-template-columns: 1fr;
			}
			.brand-row {
				align-items: flex-start;
			}
		}
		#boot-error {
			display: none;
			margin-top: 18px;
			padding: 12px 14px;
			border-radius: 12px;
			background: rgba(255, 107, 107, 0.16);
			color: #ffd4d4;
			border: 1px solid rgba(255, 107, 107, 0.24);
		}
		.first-pixel .panel {
			border-color: rgba(97, 218, 251, 0.18);
		}
		.first-pixel-status {
			margin: 0;
			font-size: 0.9rem;
			color: #8ca2c7;
		}
	</style>
</head>
<body>
	<div id="gwc-first-pixel" class="shell first-pixel" data-gwc-first-pixel="true" role="status" aria-live="polite">
		<div class="panel">
			<div class="brand-row">
				<div class="brand-mark">GWC</div>
				<div>
					<p class="eyebrow">GoWebComponents Starter</p>
					<p class="brand-copy">Preparing __GWC_PROJECT_TITLE__</p>
				</div>
			</div>
			<h1>__GWC_PROJECT_TITLE__</h1>
			<p class="first-pixel-status">Starting the wasm app...</p>
		</div>
	</div>
	<div id="app"></div>
	<div id="boot-error"></div>
	<script>
		const go = new Go();
		const errorBox = document.getElementById('boot-error');
		const appRoot = document.getElementById('app');
		const firstPixel = document.getElementById('gwc-first-pixel');
		const removeFirstPixel = () => {
			if (appRoot && appRoot.children.length > 0 && firstPixel && firstPixel.isConnected) {
				firstPixel.remove();
			}
		};
		if (appRoot && firstPixel && typeof MutationObserver === 'function') {
			new MutationObserver(removeFirstPixel).observe(appRoot, { childList: true });
		}
		WebAssembly.instantiateStreaming(fetch('./__GWC_WASM_PATH__'), go.importObject)
			.then(result => {
				removeFirstPixel();
				return go.run(result.instance);
			})
			.catch(error => {
				errorBox.style.display = 'block';
				errorBox.textContent = 'Failed to start wasm app: ' + String(error);
				console.error(error);
			});
	</script>
</body>
</html>
`
	parseRendered := strings.ReplaceAll(parseTemplate, "__GWC_PROJECT_TITLE__", parseSelection.ProjectName)
	return strings.ReplaceAll(parseRendered, "__GWC_WASM_PATH__", scaffoldWASMOutputPath())
}

func renderScaffoldMetadata(parseSelection startSelection) string {
	parsePayload := defaultScaffoldMetadata(parseSelection)
	parseEncoded, parseErr := scaffoldMarshalIndent(parsePayload, "", "  ")
	if parseErr != nil {
		return "{}\n"
	}
	return string(parseEncoded) + "\n"
}

func renderScaffoldREADME(parseSelection startSelection) string {
	parseNormalizedFeatures := startSelectionFeatures(parseSelection)
	var parseBuilder strings.Builder
	parseBuilder.WriteString(fmt.Sprintf("# %s\n\n", parseSelection.ProjectName))
	parseBuilder.WriteString(fmt.Sprintf("%s\n\n", parseSelection.Description))
	parseBuilder.WriteString(fmt.Sprintf("- Author: %s\n", parseSelection.Author))
	parseBuilder.WriteString(fmt.Sprintf("- Version: %s\n", parseSelection.Version))
	parseBuilder.WriteString(fmt.Sprintf("- Preset: %s\n\n", parseSelection.Preset.Key))

	parseBuilder.WriteString("## Selected Capabilities\n\n")
	if len(parseNormalizedFeatures) == 0 {
		parseBuilder.WriteString("- none\n")
	} else {
		for _, parseFeature := range parseNormalizedFeatures {
			parseBuilder.WriteString(fmt.Sprintf("- `%s`\n", parseFeature))
		}
	}
	parseBuilder.WriteString("\n")
	if len(parseSelection.EnabledEnterpriseSections) > 0 {
		parseBuilder.WriteString("## Enterprise Extensions\n\n")
		parseBuilder.WriteString("These optional sections came from enterprise launcher plugins and were selected during `gwc start`.\n\n")
		for _, parseSection := range parseSelection.EnabledEnterpriseSections {
			parseBuilder.WriteString(fmt.Sprintf("- %s\n", parseSection))
		}
		parseBuilder.WriteString("\n")
	}
	parseBuilder.WriteString("The full generated capability contract lives in `FEATURE_MATRIX.md`.\n\n")

	parseBuilder.WriteString("## Starter Output Rules\n\n")
	parseBuilder.WriteString("- keep generated files small, readable, and conventionally organized\n")
	parseBuilder.WriteString("- treat this scaffold as disposable starter code; edit or replace it when the app shape changes\n")
	parseBuilder.WriteString("- keep app code on public framework packages instead of importing repo-internal build tooling\n")
	parseBuilder.WriteString("- avoid coupling to monorepo-only paths so this project can live independently\n\n")

	parseBuilder.WriteString("## Run\n\n")
	parseBuilder.WriteString("From the GoWebComponents repo root:\n\n")
	parseBuilder.WriteString("```powershell\n")
	parseBuilder.WriteString(fmt.Sprintf("go run ./tools/gwc dev -app %q -root %q -html %q -wasm %q\n", filepath.Join(parseSelection.TargetDir, "main.go"), parseSelection.TargetDir, filepath.Join(parseSelection.TargetDir, "index.html"), scaffoldWASMOutputPath()))
	parseBuilder.WriteString("```\n")

	parseBuilder.WriteString("\n## Verify\n\n")
	parseBuilder.WriteString("From the generated project directory:\n\n")
	parseBuilder.WriteString("```powershell\n")
	parseBuilder.WriteString("go test ./...\n")
	parseBuilder.WriteString("```\n")
	if scaffoldHasFeature(parseNormalizedFeatures, "browser-tests") {
		parseBuilder.WriteString("\nFor browser tests, start from `test/playwrightgo/smoke_test.go` and run:\n\n")
		parseBuilder.WriteString("```powershell\n")
		parseBuilder.WriteString("go test -tags playwrightgo ./test/playwrightgo -run TestMainSuite -v\n")
		parseBuilder.WriteString("```\n")
	}
	return parseBuilder.String()
}
