// Code generated by `gwc routes gen`; DO NOT EDIT.

package typedroutesdemo

import "net/url"

// Typed, compile-checked link constructors for the route contracts in this package.
// A missing or misnamed path parameter is now a compile error, not a runtime one.
// Each route also gets a *WithQuery variant that appends typed search params.

// LinkHome builds a URL for the "/" route.
func LinkHome() string {
	return HomeRoute.MustHref(nil, nil)
}

// LinkHomeWithQuery builds a URL for the "/" route with search params appended.
func LinkHomeWithQuery(query url.Values) string {
	return HomeRoute.MustHref(nil, query)
}

// LinkPost builds a URL for the "/users/:id/posts/:postID" route.
func LinkPost(id string, postID string) string {
	return PostRoute.MustHref(map[string]string{"id": id, "postID": postID}, nil)
}

// LinkPostWithQuery builds a URL for the "/users/:id/posts/:postID" route with search params appended.
func LinkPostWithQuery(id string, postID string, query url.Values) string {
	return PostRoute.MustHref(map[string]string{"id": id, "postID": postID}, query)
}

// LinkUser builds a URL for the "/users/:id" route.
func LinkUser(id string) string {
	return UserRoute.MustHref(map[string]string{"id": id}, nil)
}

// LinkUserWithQuery builds a URL for the "/users/:id" route with search params appended.
func LinkUserWithQuery(id string, query url.Values) string {
	return UserRoute.MustHref(map[string]string{"id": id}, query)
}
