//go:build !js || !wasm

// Code generated by `gwc server gen`; DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/monstercameron/GoWebComponents/v6/serverfn"
)

// RegisterServerFunctions wires every //gwc:server function in this package onto mux.
// Call it once when building the server's HTTP handler.
func RegisterServerFunctions(parseMux *http.ServeMux) {
	serverfn.Handle(parseMux, "ListWarehouses", ListWarehouses)
}
