//go:build js && wasm

// Code generated by `gwc server gen`; DO NOT EDIT.

package api

import (
	"context"

	"github.com/monstercameron/GoWebComponents/v5/serverfn"
)

// Browser-side stubs: each calls its server function over HTTP with full type safety.

// ListWarehouses invokes the "ListWarehouses" server function from the browser.
func ListWarehouses(parseCtx context.Context, parseReq ListWarehousesRequest) (ListWarehousesResponse, error) {
	return serverfn.Call[ListWarehousesRequest, ListWarehousesResponse](parseCtx, "ListWarehouses", parseReq)
}
