//go:build js && wasm

// Package catalog provides the WASM-side emergency fallback localization bundle.
// It contains English-only strings and is intentionally minimal so it compiles into
// the smallest WASM binary possible.  The server delivers the full locale-correct
// catalog via GetCatalogBootstrap; these strings are only used during the window
// between first render and gRPC connection, and as a last-resort fallback when the
// server is unreachable.
package catalog

import "github.com/monstercameron/GoWebComponents/i18n"

const chatI18nNamespace = "chat"
const marketingI18nNamespace = "marketing"

// BuildBundle builds the emergency client-side localization bundle.
// Only English (EN) is registered here.  Additional locales are fetched from the
// server catalog RPC and merged at runtime.
func BuildBundle() *i18n.Bundle {
	bundle := i18n.NewBundle(i18n.BundleOptions{DefaultLocale: "en", FallbackLocale: "en"})
	bundle.Register("en", i18n.Catalog{
		chatI18nNamespace: {
			"auth.badge":                         {Text: "GWC auth"},
			"auth.openChat":                      {Text: "Open chat"},
			"auth.connecting":                    {Text: "Connecting to the local gRPC bridge..."},
			"auth.resolving":                     {Text: "Resolving the saved session..."},
			"auth.heroTitle":                     {Text: "Run the chat experiment without a separate login site."},
			"auth.heroBody":                      {Text: "The root route now stays inside the Go/WASM app. Sign in or create an account over gRPC, then keep everything in one shell."},
			"auth.grpcBadge":                     {Text: "gRPC only"},
			"auth.grpcBody":                      {Text: "HTTP only serves the shell and static assets. Account actions now go through the chat service tunnel."},
			"auth.loginTitle":                    {Text: "Sign in"},
			"auth.loginBody":                     {Text: "Use your local experiment account to continue the current workspace."},
			"auth.signupTitle":                   {Text: "Create account"},
			"auth.signupBody":                    {Text: "Create a local account for this experiment. No separate REST auth pages."},
			"auth.signIn":                        {Text: "Sign in"},
			"auth.createAccount":                 {Text: "Create account"},
			"auth.switchToSignup":                {Text: "Need an account? Create one"},
			"auth.switchToLogin":                 {Text: "Already have an account? Sign in"},
			"auth.displayName":                   {Text: "Display name"},
			"auth.displayNamePlaceholder":        {Text: "Optional display name"},
			"auth.email":                         {Text: "Email"},
			"auth.emailPlaceholder":              {Text: "you@example.com"},
			"auth.password":                      {Text: "Password"},
			"auth.passwordPlaceholder":           {Text: "Enter a password"},
			"auth.passwordHelp":                  {Text: "Use at least 8 characters for sign up."},
			"auth.logout":                        {Text: "Sign out"},
			"empty.heading":                      {Text: "Explore the Go WASM UI experiment"},
			"empty.body":                         {Text: "Ask about Go, Golang, WebAssembly, UI patterns, or your next framework experiment."},
			"input.placeholder":                  {Text: "Message the GoWebComponents experiment..."},
			"input.disclaimer":                   {Text: "Experimental Go/WASM UI output can be wrong. Verify important details."},
			"input.threadTotal":                  {Text: "Thread total {cost}"},
			"input.threadTotalPartial":           {Text: "Thread total {cost} (partial)"},
			"input.accountTotal":                 {Text: "Account total {cost} (includes {premiumPercent}% premium)"},
			"input.accountTotalPartial":          {Text: "Account total {cost} (partial, includes {premiumPercent}% premium)"},
			"controls.provider":                  {Text: "Provider"},
			"controls.model":                     {Text: "Model"},
			"controls.intelligence":              {Text: "Intelligence"},
			"controls.capabilityThinkingFilter":  {Text: "Reasoning mode is on, so only reasoning-capable models are shown."},
			"sidebar.newChat":                    {Text: "New chat"},
			"sidebar.threads":                    {Text: "Threads"},
			"sidebar.newFolder":                  {Text: "New folder"},
			"sidebar.newFolderShort":             {Text: "Folder"},
			"sidebar.renameFolder":               {Text: "Rename folder"},
			"sidebar.renameConversation":         {Text: "Rename conversation"},
			"sidebar.dropThreadsHere":            {Text: "Drop threads here"},
			"sidebar.unfiled":                    {Text: "Unfiled"},
			"sidebar.noConversations":            {Text: "No conversations yet"},
			"sidebar.emptyConversation":          {Text: "Empty conversation"},
			"sidebar.editSettings":               {Text: "Edit settings"},
			"sidebar.deleteConversation":         {Text: "Delete conversation"},
			"quote.prompt":                       {Text: "Quote text"},
			"canvas.badge":                       {Text: "Canvas"},
			"canvas.title":                       {Text: "Live preview"},
			"canvas.caption":                     {Text: "Latest ```canvas block"},
			"message.thinking":                   {Text: "Thinking"},
			"thread.replyComplete":               {Text: "Assistant reply complete"},
			"shell.densityCompact":               {Text: "Compact"},
			"shell.densityComfortable":           {Text: "Comfortable"},
			"message.live":                       {Text: "Live"},
			"message.switchedTo":                 {Text: "switched to {model}"},
			"message.cancel":                     {Text: "Cancel"},
			"message.saveResend":                 {Text: "Save and resend"},
			"message.copy":                       {Text: "Copy"},
			"message.edit":                       {Text: "Edit"},
			"message.fork":                       {Text: "Fork"},
			"assistant.loading":                  {Text: "Loading"},
			"assistant.pause":                    {Text: "Pause"},
			"assistant.play":                     {Text: "Play"},
			"assistant.stop":                     {Text: "Stop"},
			"assistant.speechUnavailable":        {Text: "Speech unavailable"},
			"modal.deleteTitle":                  {Text: "Delete conversation?"},
			"modal.deleteBody":                   {Text: "This will permanently delete this chat and all its messages. This cannot be undone."},
			"modal.speechProviderTitle":          {Text: "Enable OpenAI TTS?"},
			"modal.speechProviderBody":           {Text: "Your current provider does not support speech synthesis. Enable OpenAI TTS while keeping your current chat provider/model?"},
			"modal.speechProviderConfirm":        {Text: "Enable OpenAI TTS"},
			"modal.speechProviderUnavailable":    {Text: "No speech-capable OpenAI model is currently available for this account."},
			"modal.settingsTitle":                {Text: "Settings"},
			"modal.displayName":                  {Text: "Display name"},
			"modal.displayNamePlaceholder":       {Text: "Your name in chats and workspace"},
			"modal.aiTone":                       {Text: "AI tone"},
			"modal.intelligence":                 {Text: "Reasoning"},
			"modal.intelligenceHelp":             {Text: "Sets the default reasoning level used when switching providers or models."},
			"modal.intelligenceUnavailable":      {Text: "The currently selected model does not expose reasoning controls."},
			"modal.ttsProviders":                 {Text: "Voice"},
			"modal.ttsProvidersHelp":             {Text: "Select which service reads assistant replies aloud."},
			"modal.ttsProviderUnavailable":       {Text: "No supported speech model is available for this provider right now."},
			"modal.systemPrompt":                 {Text: "System prompt"},
			"modal.systemPromptPlaceholder":      {Text: "Example: Be friendly and clear. Today is {{date}} at {{time}}. Use this context when it helps:\n{{memories}}"},
			"modal.systemPromptHelp":             {Text: "These instructions are added on top of the built-in assistant prompt for your account. Template variables: {{date}}, {{time}}, {{memories}}."},
			"modal.systemPromptTemplate":         {Text: "Friendly starter:\n- Keep the response warm and practical.\n- Mention date {{date}} and time {{time}} only when relevant.\n- Use remembered context when useful:\n{{memories}}"},
			"modal.systemPromptStatusDefault":    {Text: "Default"},
			"modal.systemPromptStatusCustom":     {Text: "Custom"},
			"modal.memories":                     {Text: "Remembered preferences"},
			"modal.memoriesHelp":                 {Text: "What the assistant remembers about you across sessions."},
			"modal.memoriesEmpty":                {Text: "No remembered preferences yet."},
			"modal.memoryAdd":                    {Text: "Add memory"},
			"modal.memoryItem":                   {Text: "Profile item"},
			"modal.memoryDelete":                 {Text: "Delete"},
			"modal.memoryCategoryPlaceholder":    {Text: "Category, for example preference or project"},
			"modal.memorySummaryPlaceholder":     {Text: "Short summary"},
			"modal.memoryDetailPlaceholder":      {Text: "Optional detail"},
			"modal.memoryReasonPlaceholder":      {Text: "Why this matters"},
			"modal.language":                     {Text: "Language"},
			"modal.save":                         {Text: "Save"},
			"tone.balanced.label":                {Text: "Balanced"},
			"tone.balanced.desc":                 {Text: "Helpful and conversational"},
			"tone.friendly.label":                {Text: "Friendly"},
			"tone.friendly.desc":                 {Text: "Warm and approachable"},
			"tone.professional.label":            {Text: "Professional"},
			"tone.professional.desc":             {Text: "Formal and precise"},
			"tone.concise.label":                 {Text: "Concise"},
			"tone.concise.desc":                  {Text: "Brief and to the point"},
			"thinking.off":                       {Text: "Off"},
			"thinking.low":                       {Text: "Low"},
			"thinking.medium":                    {Text: "Med"},
			"thinking.high":                      {Text: "Hi"},
			"error.genericPrefix":                {Text: "ERROR"},
			"error.receivePrefix":                {Text: "ERROR recv:"},
			"tts.audioPlaybackFailed":            {Text: "Audio playback failed"},
			"tts.audioUnavailable":               {Text: "Audio output is unavailable in this browser"},
			"tts.audioCouldNotStart":             {Text: "Audio playback could not start"},
			"tts.audioCouldNotResume":            {Text: "Audio playback could not resume"},
			"tts.noText":                         {Text: "Nothing to read aloud"},
			"tts.connectionNotReady":             {Text: "Chat connection is not ready yet"},
			"tts.speechSynthesisFailed":          {Text: "Speech synthesis failed"},
			"tts.speechSynthesisReturnedNoAudio": {Text: "Speech synthesis returned no audio"},
			"modal.profileEmailLabel":            {Text: "Account email"},
			"modal.profileUsageTitle":            {Text: "This month's usage"},
			"modal.profileUsageLoading":          {Text: "Usage data is being calculated..."},
			"modal.profileUsageThreads":          {Text: "{count} conversations"},
			"modal.profileUsageTotalSpend":       {Text: "Total spend"},
			"modal.profileUsagePartial":          {Text: "Partial"},
			"modal.billingTitle":                 {Text: "Billing \u0026 usage"},
			"modal.billingHelp":                  {Text: "Your bill is a flat platform fee plus metered model usage and a small service premium. Each item appears separately on your invoice."},
			"modal.billingNavSummary":            {Text: "Your current plan and this month's spend"},
			"modal.billingPlanLabel":             {Text: "Current plan"},
			"modal.billingPlanValue":             {Text: "Pro"},
			"modal.billingPlatformFee":           {Text: "Platform fee"},
			"modal.billingUsageCost":             {Text: "Raw usage cost"},
			"modal.billingPremiumCost":           {Text: "Service premium"},
			"modal.billingTotalCost":             {Text: "Total"},
			"modal.billingCoverageLabel":         {Text: "Coverage"},
			"modal.billingNoUsage":               {Text: "No usage data recorded yet."},
		},
		marketingI18nNamespace: {
			// brand
			"brand.name":    {Text: "RelayDesk"},
			"brand.tagline": {Text: "AI Workspace"},
			"brand.blurb":   {Text: "Clear AI for teams that need answers, not complexity."},
			// header / nav
			"header.logIn":     {Text: "Log in"},
			"header.signUp":    {Text: "Sign up"},
			"header.openApp":   {Text: "Open app"},
			"nav.product":      {Text: "Product"},
			"nav.pricing":      {Text: "Pricing"},
			"nav.capabilities": {Text: "Capabilities"},
			"nav.plans":        {Text: "Plans"},
			"nav.compare":      {Text: "Compare"},
			"nav.faq":          {Text: "FAQ"},
			"nav.language":     {Text: "Language"},
			// footer
			"footer.copyright":          {Text: "\u00a9 2026 RelayDesk, Inc. All rights reserved."},
			"footer.privacy":            {Text: "Privacy"},
			"footer.terms":              {Text: "Terms"},
			"footer.status":             {Text: "Status"},
			"footer.col.product":        {Text: "Product"},
			"footer.col.company":        {Text: "Company"},
			"footer.col.resources":      {Text: "Resources"},
			"footer.col.legal":          {Text: "Legal"},
			"footer.col.pricing":        {Text: "Pricing"},
			"footer.link.overview":      {Text: "Overview"},
			"footer.link.home":          {Text: "Home"},
			"footer.link.signup":        {Text: "Sign up"},
			"footer.link.demo":          {Text: "Demo"},
			"footer.link.pricing":       {Text: "Pricing"},
			"footer.link.capabilities":  {Text: "Capabilities"},
			"footer.link.about":         {Text: "About"},
			"footer.link.customers":     {Text: "Customers"},
			"footer.link.careers":       {Text: "Careers"},
			"footer.link.contact":       {Text: "Contact"},
			"footer.link.documentation": {Text: "Documentation"},
			"footer.link.security":      {Text: "Security"},
			"footer.link.support":       {Text: "Support"},
			"footer.link.starter":       {Text: "Starter"},
			"footer.link.team":          {Text: "Team"},
			"footer.link.enterprise":    {Text: "Enterprise"},
			// page titles
			"page.title.home":         {Text: "RelayDesk \u2013 AI Chat Workspace"},
			"page.title.pricing":      {Text: "RelayDesk \u2013 Pricing"},
			"page.title.capabilities": {Text: "RelayDesk \u2013 Capabilities"},
			"page.title.about":        {Text: "RelayDesk \u2013 About"},
			"page.title.contact":      {Text: "RelayDesk \u2013 Contact"},
			"page.title.privacy":      {Text: "RelayDesk \u2013 Privacy"},
			"page.title.terms":        {Text: "RelayDesk \u2013 Terms"},
			"page.title.security":     {Text: "RelayDesk \u2013 Security"},
			"page.title.status":       {Text: "RelayDesk \u2013 Status"},
			// section dividers
			"divider.capabilities": {Text: "Capabilities"},
			"divider.whyTeamsBuy":  {Text: "Why teams buy"},
			"divider.pricing":      {Text: "Pricing"},
			// hero — home
			"hero.home.eyebrow":      {Text: "AI chat for support, ops, and knowledge teams"},
			"hero.home.headline":     {Text: "AI chat for teams that need faster answers and fewer repeat questions."},
			"hero.home.body":         {Text: "RelayDesk turns shared prompts, model routing, and admin visibility into one reliable workspace for support, ops, and customer-facing teams."},
			"hero.home.primaryCta":   {Text: "Create your workspace"},
			"hero.home.secondaryCta": {Text: "See pricing"},
			// hero — capabilities
			"hero.capabilities.eyebrow":      {Text: "Under the hood"},
			"hero.capabilities.headline":     {Text: "Every model. One workflow."},
			"hero.capabilities.body":         {Text: "Switch between frontier models without rebuilding your prompt stack. RelayDesk handles routing, context, and formatting so you ship faster."},
			"hero.capabilities.primaryCta":   {Text: "Start free"},
			"hero.capabilities.secondaryCta": {Text: "See pricing"},
			// hero — pricing
			"hero.pricing.eyebrow":      {Text: "Simple, honest pricing"},
			"hero.pricing.headline":     {Text: "Seat-based pricing. No usage surprises."},
			"hero.pricing.body":         {Text: "Usage-based billing with a clear platform fee. Model availability follows your configured catalog, and enterprise planning support is available on request."},
			"hero.pricing.primaryCta":   {Text: "Start free"},
			"hero.pricing.secondaryCta": {Text: "See what\u2019s included"},
			"hero.pricing.stat1.title":  {Text: "Monthly platform fee"},
			"hero.pricing.stat1.body":   {Text: "A flat workspace fee billed monthly. Covers your seat, history, and admin surface \u2014 not model calls."},
			"hero.pricing.stat2.title":  {Text: "Actual AI usage"},
			"hero.pricing.stat2.body":   {Text: "Model calls billed at cost. Shown as a separate line item so you always see raw cost plus the RelayDesk service premium."},
			"hero.pricing.stat3.title":  {Text: "Service premium"},
			"hero.pricing.stat3.body":   {Text: "A small markup over raw model cost, shown separately on every invoice. No hidden multipliers."},
			// metric strip
			"metric.responseTime.value": {Text: "Workspace controls"},
			"metric.responseTime.label": {Text: "Admin visibility built in"},
			"metric.models.value":       {Text: "Model flexibility"},
			"metric.models.label":       {Text: "Route to the right model"},
			"metric.uptime.value":       {Text: "Operational visibility"},
			"metric.uptime.label":       {Text: "Usage and cost reporting"},
			"metric.live":               {Text: "live"},
			// demo card
			"demo.brandLabel":        {Text: "RelayDesk"},
			"demo.model":             {Text: "gpt-4o \u00b7 streaming"},
			"demo.live":              {Text: "live"},
			"demo.question":          {Text: "Which vendor will be easiest for my team to adopt?"},
			"demo.answer":            {Text: "Comparing rollout friction, training burden, pricing clarity, and day-one usability \u2014 safest option first."},
			"demo.reply":             {Text: "Keep it simple. My team is not technical."},
			"demo.chip.setup.label":  {Text: "Setup"},
			"demo.chip.setup.value":  {Text: "Guided rollout"},
			"demo.chip.output.label": {Text: "Output"},
			"demo.chip.output.value": {Text: "Plain language"},
			"demo.chip.value.label":  {Text: "Value"},
			"demo.chip.value.value":  {Text: "Same-day clarity"},
			"demo.composer.prompt":   {Text: "Ask about your workflow\u2026"},
			// product section — home
			"product.home.eyebrow":                {Text: "Built for support, ops, and internal knowledge teams"},
			"product.home.h2":                     {Text: "One workspace for questions, workflows, and admin control."},
			"product.home.body":                   {Text: "Use RelayDesk to answer repeat questions faster, standardize team responses, review usage in one workspace, and keep admins in control of cost, access, and model behavior."},
			"product.home.card.responses.title":   {Text: "< 800ms responses"},
			"product.home.card.responses.body":    {Text: "GPT-4o streaming by default. Switch to Claude or Gemini per-thread with one click."},
			"product.home.card.docqa.title":       {Text: "Shared workflows"},
			"product.home.card.docqa.body":        {Text: "Keep prompt patterns, thread history, and model choices visible in one workspace so the team can repeat what works."},
			"product.home.card.decisionlog.title": {Text: "Decision log"},
			"product.home.card.decisionlog.body":  {Text: "Every answer is timestamped and citable. Create an audit trail for your team\u2019s AI-assisted choices."},
			"product.home.card.enterprise.title":  {Text: "Enterprise-ready"},
			"product.home.card.enterprise.body":   {Text: "Role-based access, audit visibility, spending controls, and guided rollout support built around the shipped runtime."},
			// product section — capabilities
			"product.capabilities.eyebrow":               {Text: "Under the hood"},
			"product.capabilities.h2":                    {Text: "Designed to replace four tools with one."},
			"product.capabilities.body":                  {Text: "Chat assistant, shared workflows, and usage visibility \u2014 all in a single workspace your team already understands."},
			"product.capabilities.card.routing.title":    {Text: "Intent routing"},
			"product.capabilities.card.routing.body":     {Text: "Requests are classified and routed before the model call, cutting average response cost by 30\u201340%."},
			"product.capabilities.card.drafting.title":   {Text: "On-brand drafting"},
			"product.capabilities.card.drafting.body":    {Text: "System-level voice and tone guidance ensure every answer sounds like your team, not a generic bot."},
			"product.capabilities.card.escalation.title": {Text: "Escalation with context"},
			"product.capabilities.card.escalation.body":  {Text: "Human handoffs include a summary, sentiment score, and recommended next action \u2014 no re-reads."},
			"product.capabilities.card.usage.title":      {Text: "Usage transparency"},
			"product.capabilities.card.usage.body":       {Text: "Live usage totals, model breakdown, and spend cap alerts on every seat."},
			// why section
			"why.eyebrow":       {Text: "Why teams choose RelayDesk"},
			"why.quote":         {Text: "\u201cYou\u2019re not just buying AI access. You\u2019re buying fewer repeat questions, cleaner handoffs, and less operational drag.\u201d"},
			"why.body":          {Text: "Designed for teams that need grounded answers, cleaner handoffs, and clear visibility into usage."},
			"why.primaryCta":    {Text: "Create your workspace"},
			"why.secondaryCta":  {Text: "See pricing"},
			"why.proof1.number": {Text: "Workspace controls"},
			"why.proof1.title":  {Text: "Admin visibility built in"},
			"why.proof1.body":   {Text: "Control cost, access, and model behavior across every workspace member from one admin view."},
			"why.proof2.number": {Text: "Model flexibility"},
			"why.proof2.title":  {Text: "Route to the right model"},
			"why.proof2.body":   {Text: "Switch between GPT-4o, Claude, and Gemini per thread without rebuilding your workflow."},
			"why.proof3.number": {Text: "Operational visibility"},
			"why.proof3.title":  {Text: "Clear usage and cost reporting"},
			"why.proof3.body":   {Text: "Track usage events, spending, and model cost across your workspace from day one."},
			// pricing section cards
			"pricing.section.eyebrow":   {Text: "Pricing"},
			"pricing.section.h2":        {Text: "Usage-based pricing with a clear platform fee."},
			"pricing.section.body":      {Text: "Pay a monthly RelayDesk fee plus actual AI usage, with a small service premium that keeps billing predictable and the product sustainable."},
			"pricing.starter.name":      {Text: "Starter"},
			"pricing.starter.price":     {Text: "$49"},
			"pricing.starter.suffix":    {Text: "/mo"},
			"pricing.starter.body":      {Text: "For one serious operator who wants a reliable AI workspace without team overhead."},
			"pricing.starter.badge":     {Text: ""},
			"pricing.starter.cta":       {Text: "Get started"},
			"pricing.team.name":         {Text: "Team"},
			"pricing.team.price":        {Text: "$149"},
			"pricing.team.suffix":       {Text: "/mo"},
			"pricing.team.body":         {Text: "For teams that need shared workflows, admin visibility, and less chaos."},
			"pricing.team.badge":        {Text: "Most popular"},
			"pricing.team.cta":          {Text: "Get started"},
			"pricing.enterprise.name":   {Text: "Enterprise"},
			"pricing.enterprise.price":  {Text: "Custom"},
			"pricing.enterprise.suffix": {Text: ""},
			"pricing.enterprise.body":   {Text: "For organizations that need security review, procurement, SSO, and contract controls."},
			"pricing.enterprise.badge":  {Text: ""},
			"pricing.enterprise.cta":    {Text: "Talk to sales"},
			// pricing shell — hero
			"pricing.hero.eyebrow":      {Text: "Usage-based pricing \u00b7 clear platform fee"},
			"pricing.hero.headline":     {Text: "Usage-based pricing with a clear platform fee."},
			"pricing.hero.body":         {Text: "Pay a monthly RelayDesk fee plus actual AI usage, with a small service premium that keeps billing predictable and the product sustainable."},
			"pricing.hero.primaryCta":   {Text: "Explore plans"},
			"pricing.hero.secondaryCta": {Text: "Compare features"},
			// pricing shell — plans headers
			"pricing.plans.eyebrow":          {Text: "Plans"},
			"pricing.plans.h2":               {Text: "Choose the workspace that matches how you work."},
			"pricing.starter.tone":           {Text: "For solo operators"},
			"pricing.starter.description":    {Text: "One seat with a small platform fee and usage metering. Full conversation history and core model access."},
			"pricing.starter.feature.0":      {Text: "1 seat"},
			"pricing.starter.feature.1":      {Text: "GPT-4o, Claude, Gemini"},
			"pricing.starter.feature.2":      {Text: "Full history & exports"},
			"pricing.starter.feature.3":      {Text: "Document Q&A"},
			"pricing.starter.feature.4":      {Text: "Email support"},
			"pricing.team.tone":              {Text: "Most popular"},
			"pricing.team.description":       {Text: "Up to 10 seats with shared context, usage dashboard, and priority support. Same transparent usage formula."},
			"pricing.team.feature.0":         {Text: "Up to 10 seats"},
			"pricing.team.feature.1":         {Text: "Shared workspaces & threads"},
			"pricing.team.feature.2":         {Text: "Usage dashboard"},
			"pricing.team.feature.3":         {Text: "Admin controls"},
			"pricing.team.feature.4":         {Text: "Templates & presets"},
			"pricing.team.feature.5":         {Text: "Priority support"},
			"pricing.enterprise.tone":        {Text: "For larger orgs"},
			"pricing.enterprise.description": {Text: "Custom seat bands, audit visibility, policy review, rollout planning, and a tailored support path."},
			"pricing.enterprise.feature.0":   {Text: "Custom seat bands"},
			"pricing.enterprise.feature.1":   {Text: "Access policy review"},
			"pricing.enterprise.feature.2":   {Text: "Audit log & usage review"},
			"pricing.enterprise.feature.3":   {Text: "Custom model routing"},
			"pricing.enterprise.feature.4":   {Text: "SLA guarantee"},
			"pricing.enterprise.feature.5":   {Text: "Dedicated success engineer"},
			// compare table
			"compare.eyebrow":               {Text: "Compare"},
			"compare.h2":                    {Text: "What changes as you move up."},
			"compare.col.capability":        {Text: "Capability"},
			"compare.col.starter":           {Text: "Starter"},
			"compare.col.team":              {Text: "Team"},
			"compare.col.enterprise":        {Text: "Enterprise"},
			"compare.workspace.label":       {Text: "Workspace mode"},
			"compare.workspace.starter":     {Text: "Solo (1 seat)"},
			"compare.workspace.team":        {Text: "Shared (up to 10)"},
			"compare.workspace.enterprise":  {Text: "Custom seat bands"},
			"compare.collab.label":          {Text: "Collaboration"},
			"compare.collab.starter":        {Text: "Private threads"},
			"compare.collab.team":           {Text: "Shared threads + context"},
			"compare.collab.enterprise":     {Text: "+ enterprise controls"},
			"compare.admin.label":           {Text: "Admin controls"},
			"compare.admin.starter":         {Text: "Basic"},
			"compare.admin.team":            {Text: "Full dashboard"},
			"compare.admin.enterprise":      {Text: "Advanced"},
			"compare.billing.label":         {Text: "Billing visibility"},
			"compare.billing.starter":       {Text: "Usage summary"},
			"compare.billing.team":          {Text: "Per-member breakdown"},
			"compare.billing.enterprise":    {Text: "Custom reporting"},
			"compare.support.label":         {Text: "Support"},
			"compare.support.starter":       {Text: "Email"},
			"compare.support.team":          {Text: "Priority"},
			"compare.support.enterprise":    {Text: "Dedicated engineer"},
			"compare.compliance.label":      {Text: "Security / compliance"},
			"compare.compliance.starter":    {Text: "Encrypted, US region"},
			"compare.compliance.team":       {Text: "+ audit events"},
			"compare.compliance.enterprise": {Text: "DPA, audit review, policy planning"},
			// pricing FAQ (structural — answers served by server catalog)
			"faq.eyebrow": {Text: "FAQ"},
			"faq.h2":      {Text: "Questions buyers ask first."},
			"faq.body":    {Text: "Anything not covered here? Email us at hello@relaydesk.com and we\u2019ll get back within one business day."},
			"faq.q1.q":    {Text: "What is the platform fee?"},
			"faq.q2.q":    {Text: "How is usage billed?"},
			"faq.q3.q":    {Text: "What is the service premium?"},
			"faq.q4.q":    {Text: "When do I need Team instead of Starter?"},
			"faq.q5.q":    {Text: "How do I contact sales?"},
			// contact
			"contact.eyebrow":    {Text: "Enterprise"},
			"contact.h2":         {Text: "Need a tailored deployment for your team?"},
			"contact.body":       {Text: "We will scope a plan around your workflow, compliance requirements, and seat count. No generic packages."},
			"contact.emailSales": {Text: "Email sales"},
			"contact.emailTeam":  {Text: "Contact the team"},
		},
	})
	return bundle
}
