// Code generated by `gwc routes gen`; DO NOT EDIT.

package typedroutesdemo

// Typed, compile-checked link constructors for the route contracts in this package.
// A missing or misnamed path parameter is now a compile error, not a runtime one.

// LinkHome builds a URL for the "/" route.
func LinkHome() string {
	return HomeRoute.MustHref(nil, nil)
}

// LinkPost builds a URL for the "/users/:id/posts/:postID" route.
func LinkPost(id string, postID string) string {
	return PostRoute.MustHref(map[string]string{
		"id":     id,
		"postID": postID,
	}, nil)
}

// LinkUser builds a URL for the "/users/:id" route.
func LinkUser(id string) string {
	return UserRoute.MustHref(map[string]string{
		"id": id,
	}, nil)
}
