// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/chat.proto

package chatpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatService_Signup_FullMethodName                     = "/chat.v1.ChatService/Signup"
	ChatService_Login_FullMethodName                      = "/chat.v1.ChatService/Login"
	ChatService_Logout_FullMethodName                     = "/chat.v1.ChatService/Logout"
	ChatService_GetSession_FullMethodName                 = "/chat.v1.ChatService/GetSession"
	ChatService_RefreshSession_FullMethodName             = "/chat.v1.ChatService/RefreshSession"
	ChatService_GetClientIdentity_FullMethodName          = "/chat.v1.ChatService/GetClientIdentity"
	ChatService_ReportClientLog_FullMethodName            = "/chat.v1.ChatService/ReportClientLog"
	ChatService_GetLogTail_FullMethodName                 = "/chat.v1.ChatService/GetLogTail"
	ChatService_GetServerToolPolicy_FullMethodName        = "/chat.v1.ChatService/GetServerToolPolicy"
	ChatService_SetServerToolPolicy_FullMethodName        = "/chat.v1.ChatService/SetServerToolPolicy"
	ChatService_GetAdminDashboard_FullMethodName          = "/chat.v1.ChatService/GetAdminDashboard"
	ChatService_GetSuperuserControlPlane_FullMethodName   = "/chat.v1.ChatService/GetSuperuserControlPlane"
	ChatService_ListAdminUsers_FullMethodName             = "/chat.v1.ChatService/ListAdminUsers"
	ChatService_ListAdminUsageEvents_FullMethodName       = "/chat.v1.ChatService/ListAdminUsageEvents"
	ChatService_ListAdminConversations_FullMethodName     = "/chat.v1.ChatService/ListAdminConversations"
	ChatService_RunServerTool_FullMethodName              = "/chat.v1.ChatService/RunServerTool"
	ChatService_Send_FullMethodName                       = "/chat.v1.ChatService/Send"
	ChatService_ListConversations_FullMethodName          = "/chat.v1.ChatService/ListConversations"
	ChatService_ResolveConversationRoute_FullMethodName   = "/chat.v1.ChatService/ResolveConversationRoute"
	ChatService_LoadConversation_FullMethodName           = "/chat.v1.ChatService/LoadConversation"
	ChatService_DeleteConversation_FullMethodName         = "/chat.v1.ChatService/DeleteConversation"
	ChatService_SetUserName_FullMethodName                = "/chat.v1.ChatService/SetUserName"
	ChatService_GetUserName_FullMethodName                = "/chat.v1.ChatService/GetUserName"
	ChatService_ListUserMemories_FullMethodName           = "/chat.v1.ChatService/ListUserMemories"
	ChatService_UpsertUserMemory_FullMethodName           = "/chat.v1.ChatService/UpsertUserMemory"
	ChatService_DeleteUserMemory_FullMethodName           = "/chat.v1.ChatService/DeleteUserMemory"
	ChatService_SynthesizeSpeech_FullMethodName           = "/chat.v1.ChatService/SynthesizeSpeech"
	ChatService_ListModelOptions_FullMethodName           = "/chat.v1.ChatService/ListModelOptions"
	ChatService_SetSelectedModel_FullMethodName           = "/chat.v1.ChatService/SetSelectedModel"
	ChatService_GetSelectedModel_FullMethodName           = "/chat.v1.ChatService/GetSelectedModel"
	ChatService_SetSelectedTone_FullMethodName            = "/chat.v1.ChatService/SetSelectedTone"
	ChatService_GetSelectedTone_FullMethodName            = "/chat.v1.ChatService/GetSelectedTone"
	ChatService_SetSelectedThinkingEnabled_FullMethodName = "/chat.v1.ChatService/SetSelectedThinkingEnabled"
	ChatService_GetSelectedThinkingEnabled_FullMethodName = "/chat.v1.ChatService/GetSelectedThinkingEnabled"
	ChatService_SetSelectedThinkingEffort_FullMethodName  = "/chat.v1.ChatService/SetSelectedThinkingEffort"
	ChatService_GetSelectedThinkingEffort_FullMethodName  = "/chat.v1.ChatService/GetSelectedThinkingEffort"
	ChatService_SetCustomSystemPrompt_FullMethodName      = "/chat.v1.ChatService/SetCustomSystemPrompt"
	ChatService_GetCustomSystemPrompt_FullMethodName      = "/chat.v1.ChatService/GetCustomSystemPrompt"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChatService bridges the browser to an OpenAI streaming completion.
type ChatServiceClient interface {
	// Signup creates a new user account and returns a signed auth token.
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// Login validates a user credential pair and returns a signed auth token.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// Logout is a stateless acknowledgement for client token disposal.
	Logout(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetSession resolves the current auth token, if any, into a user session.
	GetSession(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSessionResponse, error)
	// RefreshSession issues a fresh signed auth token for the current user.
	RefreshSession(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AuthResponse, error)
	// GetClientIdentity returns a stable server-issued client identity for log correlation.
	GetClientIdentity(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetClientIdentityResponse, error)
	// ReportClientLog forwards structured client telemetry to server-side logs.
	ReportClientLog(ctx context.Context, in *ReportClientLogRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetLogTail returns the latest server/client log lines for authenticated superusers.
	GetLogTail(ctx context.Context, in *GetLogTailRequest, opts ...grpc.CallOption) (*GetLogTailResponse, error)
	// GetServerToolPolicy returns server-side terminal execution policy and command whitelist.
	GetServerToolPolicy(ctx context.Context, in *GetServerToolPolicyRequest, opts ...grpc.CallOption) (*GetServerToolPolicyResponse, error)
	// SetServerToolPolicy updates server-side terminal execution policy and command whitelist.
	SetServerToolPolicy(ctx context.Context, in *SetServerToolPolicyRequest, opts ...grpc.CallOption) (*SetServerToolPolicyResponse, error)
	// GetAdminDashboard returns one admin analytics snapshot for authenticated superusers.
	GetAdminDashboard(ctx context.Context, in *GetAdminDashboardRequest, opts ...grpc.CallOption) (*GetAdminDashboardResponse, error)
	// GetSuperuserControlPlane returns the superuser control-plane snapshot for authenticated su users.
	GetSuperuserControlPlane(ctx context.Context, in *GetSuperuserControlPlaneRequest, opts ...grpc.CallOption) (*GetSuperuserControlPlaneResponse, error)
	// ListAdminUsers returns recent users with aggregate spend and activity for authenticated superusers.
	ListAdminUsers(ctx context.Context, in *ListAdminUsersRequest, opts ...grpc.CallOption) (*ListAdminUsersResponse, error)
	// ListAdminUsageEvents returns recent global usage ledger rows for authenticated superusers.
	ListAdminUsageEvents(ctx context.Context, in *ListAdminUsageEventsRequest, opts ...grpc.CallOption) (*ListAdminUsageEventsResponse, error)
	// ListAdminConversations returns recent conversations with owner and spend rollups for authenticated superusers.
	ListAdminConversations(ctx context.Context, in *ListAdminConversationsRequest, opts ...grpc.CallOption) (*ListAdminConversationsResponse, error)
	// RunServerTool opens a bidirectional terminal-execution bridge for approved server tools.
	RunServerTool(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunServerToolRequest, RunServerToolEvent], error)
	// Send starts a server-streaming RPC. The client sends one request and
	// receives a stream of ChatChunk messages until done=true.
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatChunk], error)
	// ListConversations returns all stored conversations newest-first with a preview.
	ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error)
	// ResolveConversationRoute maps a public UUID route to one accessible conversation.
	ResolveConversationRoute(ctx context.Context, in *ResolveConversationRouteRequest, opts ...grpc.CallOption) (*ResolveConversationRouteResponse, error)
	// LoadConversation returns the full message history for a given conversation.
	LoadConversation(ctx context.Context, in *LoadConversationRequest, opts ...grpc.CallOption) (*LoadConversationResponse, error)
	// DeleteConversation removes a conversation and all its messages permanently.
	DeleteConversation(ctx context.Context, in *DeleteConversationRequest, opts ...grpc.CallOption) (*DeleteConversationResponse, error)
	// SetUserName persists the display name for the single user profile.
	SetUserName(ctx context.Context, in *SetUserNameRequest, opts ...grpc.CallOption) (*SetUserNameResponse, error)
	// GetUserName retrieves the persisted display name; updated_at lets the client
	// decide whether its cached copy is still fresh.
	GetUserName(ctx context.Context, in *GetUserNameRequest, opts ...grpc.CallOption) (*GetUserNameResponse, error)
	// ListUserMemories returns stored per-user preference/profile memories.
	ListUserMemories(ctx context.Context, in *ListUserMemoriesRequest, opts ...grpc.CallOption) (*ListUserMemoriesResponse, error)
	// UpsertUserMemory creates or updates one stored user memory row.
	UpsertUserMemory(ctx context.Context, in *UpsertUserMemoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DeleteUserMemory removes one stored user memory row by key.
	DeleteUserMemory(ctx context.Context, in *DeleteUserMemoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// SynthesizeSpeech streams assistant text into speech audio chunks.
	SynthesizeSpeech(ctx context.Context, in *SynthesizeSpeechRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SynthesizeSpeechChunk], error)
	// ListModelOptions returns the current model catalogue advertised by configured providers.
	ListModelOptions(ctx context.Context, in *ListModelOptionsRequest, opts ...grpc.CallOption) (*ListModelOptionsResponse, error)
	// SetSelectedModel persists the preferred model for the single user profile.
	SetSelectedModel(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetSelectedModel retrieves the persisted preferred model.
	GetSelectedModel(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.StringValue, error)
	// SetSelectedTone persists the preferred tone for the single user profile.
	SetSelectedTone(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetSelectedTone retrieves the persisted preferred tone.
	GetSelectedTone(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.StringValue, error)
	// SetSelectedThinkingEnabled persists whether live reasoning/thought output is enabled.
	SetSelectedThinkingEnabled(ctx context.Context, in *wrapperspb.BoolValue, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetSelectedThinkingEnabled retrieves whether live reasoning/thought output is enabled.
	GetSelectedThinkingEnabled(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error)
	// SetSelectedThinkingEffort persists the preferred reasoning effort level.
	SetSelectedThinkingEffort(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetSelectedThinkingEffort retrieves the preferred reasoning effort level.
	GetSelectedThinkingEffort(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.StringValue, error)
	// SetCustomSystemPrompt persists user-configured system prompt additions.
	SetCustomSystemPrompt(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetCustomSystemPrompt retrieves user-configured system prompt additions.
	GetCustomSystemPrompt(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.StringValue, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, ChatService_Signup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, ChatService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) Logout(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChatService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetSession(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, ChatService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) RefreshSession(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, ChatService_RefreshSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetClientIdentity(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetClientIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClientIdentityResponse)
	err := c.cc.Invoke(ctx, ChatService_GetClientIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ReportClientLog(ctx context.Context, in *ReportClientLogRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChatService_ReportClientLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetLogTail(ctx context.Context, in *GetLogTailRequest, opts ...grpc.CallOption) (*GetLogTailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLogTailResponse)
	err := c.cc.Invoke(ctx, ChatService_GetLogTail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetServerToolPolicy(ctx context.Context, in *GetServerToolPolicyRequest, opts ...grpc.CallOption) (*GetServerToolPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerToolPolicyResponse)
	err := c.cc.Invoke(ctx, ChatService_GetServerToolPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SetServerToolPolicy(ctx context.Context, in *SetServerToolPolicyRequest, opts ...grpc.CallOption) (*SetServerToolPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetServerToolPolicyResponse)
	err := c.cc.Invoke(ctx, ChatService_SetServerToolPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetAdminDashboard(ctx context.Context, in *GetAdminDashboardRequest, opts ...grpc.CallOption) (*GetAdminDashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdminDashboardResponse)
	err := c.cc.Invoke(ctx, ChatService_GetAdminDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetSuperuserControlPlane(ctx context.Context, in *GetSuperuserControlPlaneRequest, opts ...grpc.CallOption) (*GetSuperuserControlPlaneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSuperuserControlPlaneResponse)
	err := c.cc.Invoke(ctx, ChatService_GetSuperuserControlPlane_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ListAdminUsers(ctx context.Context, in *ListAdminUsersRequest, opts ...grpc.CallOption) (*ListAdminUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminUsersResponse)
	err := c.cc.Invoke(ctx, ChatService_ListAdminUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ListAdminUsageEvents(ctx context.Context, in *ListAdminUsageEventsRequest, opts ...grpc.CallOption) (*ListAdminUsageEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminUsageEventsResponse)
	err := c.cc.Invoke(ctx, ChatService_ListAdminUsageEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ListAdminConversations(ctx context.Context, in *ListAdminConversationsRequest, opts ...grpc.CallOption) (*ListAdminConversationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminConversationsResponse)
	err := c.cc.Invoke(ctx, ChatService_ListAdminConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) RunServerTool(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunServerToolRequest, RunServerToolEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[0], ChatService_RunServerTool_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunServerToolRequest, RunServerToolEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_RunServerToolClient = grpc.BidiStreamingClient[RunServerToolRequest, RunServerToolEvent]

func (c *chatServiceClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[1], ChatService_Send_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendRequest, ChatChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_SendClient = grpc.ServerStreamingClient[ChatChunk]

func (c *chatServiceClient) ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConversationsResponse)
	err := c.cc.Invoke(ctx, ChatService_ListConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ResolveConversationRoute(ctx context.Context, in *ResolveConversationRouteRequest, opts ...grpc.CallOption) (*ResolveConversationRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveConversationRouteResponse)
	err := c.cc.Invoke(ctx, ChatService_ResolveConversationRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) LoadConversation(ctx context.Context, in *LoadConversationRequest, opts ...grpc.CallOption) (*LoadConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadConversationResponse)
	err := c.cc.Invoke(ctx, ChatService_LoadConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) DeleteConversation(ctx context.Context, in *DeleteConversationRequest, opts ...grpc.CallOption) (*DeleteConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConversationResponse)
	err := c.cc.Invoke(ctx, ChatService_DeleteConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SetUserName(ctx context.Context, in *SetUserNameRequest, opts ...grpc.CallOption) (*SetUserNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserNameResponse)
	err := c.cc.Invoke(ctx, ChatService_SetUserName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetUserName(ctx context.Context, in *GetUserNameRequest, opts ...grpc.CallOption) (*GetUserNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserNameResponse)
	err := c.cc.Invoke(ctx, ChatService_GetUserName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) ListUserMemories(ctx context.Context, in *ListUserMemoriesRequest, opts ...grpc.CallOption) (*ListUserMemoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserMemoriesResponse)
	err := c.cc.Invoke(ctx, ChatService_ListUserMemories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) UpsertUserMemory(ctx context.Context, in *UpsertUserMemoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChatService_UpsertUserMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) DeleteUserMemory(ctx context.Context, in *DeleteUserMemoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChatService_DeleteUserMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SynthesizeSpeech(ctx context.Context, in *SynthesizeSpeechRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SynthesizeSpeechChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[2], ChatService_SynthesizeSpeech_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SynthesizeSpeechRequest, SynthesizeSpeechChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_SynthesizeSpeechClient = grpc.ServerStreamingClient[SynthesizeSpeechChunk]

func (c *chatServiceClient) ListModelOptions(ctx context.Context, in *ListModelOptionsRequest, opts ...grpc.CallOption) (*ListModelOptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelOptionsResponse)
	err := c.cc.Invoke(ctx, ChatService_ListModelOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SetSelectedModel(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChatService_SetSelectedModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetSelectedModel(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.StringValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrapperspb.StringValue)
	err := c.cc.Invoke(ctx, ChatService_GetSelectedModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SetSelectedTone(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChatService_SetSelectedTone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetSelectedTone(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.StringValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrapperspb.StringValue)
	err := c.cc.Invoke(ctx, ChatService_GetSelectedTone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SetSelectedThinkingEnabled(ctx context.Context, in *wrapperspb.BoolValue, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChatService_SetSelectedThinkingEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetSelectedThinkingEnabled(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrapperspb.BoolValue)
	err := c.cc.Invoke(ctx, ChatService_GetSelectedThinkingEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SetSelectedThinkingEffort(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChatService_SetSelectedThinkingEffort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetSelectedThinkingEffort(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.StringValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrapperspb.StringValue)
	err := c.cc.Invoke(ctx, ChatService_GetSelectedThinkingEffort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SetCustomSystemPrompt(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChatService_SetCustomSystemPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetCustomSystemPrompt(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.StringValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrapperspb.StringValue)
	err := c.cc.Invoke(ctx, ChatService_GetCustomSystemPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility.
//
// ChatService bridges the browser to an OpenAI streaming completion.
type ChatServiceServer interface {
	// Signup creates a new user account and returns a signed auth token.
	Signup(context.Context, *SignupRequest) (*AuthResponse, error)
	// Login validates a user credential pair and returns a signed auth token.
	Login(context.Context, *LoginRequest) (*AuthResponse, error)
	// Logout is a stateless acknowledgement for client token disposal.
	Logout(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// GetSession resolves the current auth token, if any, into a user session.
	GetSession(context.Context, *emptypb.Empty) (*GetSessionResponse, error)
	// RefreshSession issues a fresh signed auth token for the current user.
	RefreshSession(context.Context, *emptypb.Empty) (*AuthResponse, error)
	// GetClientIdentity returns a stable server-issued client identity for log correlation.
	GetClientIdentity(context.Context, *emptypb.Empty) (*GetClientIdentityResponse, error)
	// ReportClientLog forwards structured client telemetry to server-side logs.
	ReportClientLog(context.Context, *ReportClientLogRequest) (*emptypb.Empty, error)
	// GetLogTail returns the latest server/client log lines for authenticated superusers.
	GetLogTail(context.Context, *GetLogTailRequest) (*GetLogTailResponse, error)
	// GetServerToolPolicy returns server-side terminal execution policy and command whitelist.
	GetServerToolPolicy(context.Context, *GetServerToolPolicyRequest) (*GetServerToolPolicyResponse, error)
	// SetServerToolPolicy updates server-side terminal execution policy and command whitelist.
	SetServerToolPolicy(context.Context, *SetServerToolPolicyRequest) (*SetServerToolPolicyResponse, error)
	// GetAdminDashboard returns one admin analytics snapshot for authenticated superusers.
	GetAdminDashboard(context.Context, *GetAdminDashboardRequest) (*GetAdminDashboardResponse, error)
	// GetSuperuserControlPlane returns the superuser control-plane snapshot for authenticated su users.
	GetSuperuserControlPlane(context.Context, *GetSuperuserControlPlaneRequest) (*GetSuperuserControlPlaneResponse, error)
	// ListAdminUsers returns recent users with aggregate spend and activity for authenticated superusers.
	ListAdminUsers(context.Context, *ListAdminUsersRequest) (*ListAdminUsersResponse, error)
	// ListAdminUsageEvents returns recent global usage ledger rows for authenticated superusers.
	ListAdminUsageEvents(context.Context, *ListAdminUsageEventsRequest) (*ListAdminUsageEventsResponse, error)
	// ListAdminConversations returns recent conversations with owner and spend rollups for authenticated superusers.
	ListAdminConversations(context.Context, *ListAdminConversationsRequest) (*ListAdminConversationsResponse, error)
	// RunServerTool opens a bidirectional terminal-execution bridge for approved server tools.
	RunServerTool(grpc.BidiStreamingServer[RunServerToolRequest, RunServerToolEvent]) error
	// Send starts a server-streaming RPC. The client sends one request and
	// receives a stream of ChatChunk messages until done=true.
	Send(*SendRequest, grpc.ServerStreamingServer[ChatChunk]) error
	// ListConversations returns all stored conversations newest-first with a preview.
	ListConversations(context.Context, *ListConversationsRequest) (*ListConversationsResponse, error)
	// ResolveConversationRoute maps a public UUID route to one accessible conversation.
	ResolveConversationRoute(context.Context, *ResolveConversationRouteRequest) (*ResolveConversationRouteResponse, error)
	// LoadConversation returns the full message history for a given conversation.
	LoadConversation(context.Context, *LoadConversationRequest) (*LoadConversationResponse, error)
	// DeleteConversation removes a conversation and all its messages permanently.
	DeleteConversation(context.Context, *DeleteConversationRequest) (*DeleteConversationResponse, error)
	// SetUserName persists the display name for the single user profile.
	SetUserName(context.Context, *SetUserNameRequest) (*SetUserNameResponse, error)
	// GetUserName retrieves the persisted display name; updated_at lets the client
	// decide whether its cached copy is still fresh.
	GetUserName(context.Context, *GetUserNameRequest) (*GetUserNameResponse, error)
	// ListUserMemories returns stored per-user preference/profile memories.
	ListUserMemories(context.Context, *ListUserMemoriesRequest) (*ListUserMemoriesResponse, error)
	// UpsertUserMemory creates or updates one stored user memory row.
	UpsertUserMemory(context.Context, *UpsertUserMemoryRequest) (*emptypb.Empty, error)
	// DeleteUserMemory removes one stored user memory row by key.
	DeleteUserMemory(context.Context, *DeleteUserMemoryRequest) (*emptypb.Empty, error)
	// SynthesizeSpeech streams assistant text into speech audio chunks.
	SynthesizeSpeech(*SynthesizeSpeechRequest, grpc.ServerStreamingServer[SynthesizeSpeechChunk]) error
	// ListModelOptions returns the current model catalogue advertised by configured providers.
	ListModelOptions(context.Context, *ListModelOptionsRequest) (*ListModelOptionsResponse, error)
	// SetSelectedModel persists the preferred model for the single user profile.
	SetSelectedModel(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error)
	// GetSelectedModel retrieves the persisted preferred model.
	GetSelectedModel(context.Context, *emptypb.Empty) (*wrapperspb.StringValue, error)
	// SetSelectedTone persists the preferred tone for the single user profile.
	SetSelectedTone(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error)
	// GetSelectedTone retrieves the persisted preferred tone.
	GetSelectedTone(context.Context, *emptypb.Empty) (*wrapperspb.StringValue, error)
	// SetSelectedThinkingEnabled persists whether live reasoning/thought output is enabled.
	SetSelectedThinkingEnabled(context.Context, *wrapperspb.BoolValue) (*emptypb.Empty, error)
	// GetSelectedThinkingEnabled retrieves whether live reasoning/thought output is enabled.
	GetSelectedThinkingEnabled(context.Context, *emptypb.Empty) (*wrapperspb.BoolValue, error)
	// SetSelectedThinkingEffort persists the preferred reasoning effort level.
	SetSelectedThinkingEffort(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error)
	// GetSelectedThinkingEffort retrieves the preferred reasoning effort level.
	GetSelectedThinkingEffort(context.Context, *emptypb.Empty) (*wrapperspb.StringValue, error)
	// SetCustomSystemPrompt persists user-configured system prompt additions.
	SetCustomSystemPrompt(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error)
	// GetCustomSystemPrompt retrieves user-configured system prompt additions.
	GetCustomSystemPrompt(context.Context, *emptypb.Empty) (*wrapperspb.StringValue, error)
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) Signup(context.Context, *SignupRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedChatServiceServer) Login(context.Context, *LoginRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedChatServiceServer) Logout(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedChatServiceServer) GetSession(context.Context, *emptypb.Empty) (*GetSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedChatServiceServer) RefreshSession(context.Context, *emptypb.Empty) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshSession not implemented")
}
func (UnimplementedChatServiceServer) GetClientIdentity(context.Context, *emptypb.Empty) (*GetClientIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientIdentity not implemented")
}
func (UnimplementedChatServiceServer) ReportClientLog(context.Context, *ReportClientLogRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportClientLog not implemented")
}
func (UnimplementedChatServiceServer) GetLogTail(context.Context, *GetLogTailRequest) (*GetLogTailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogTail not implemented")
}
func (UnimplementedChatServiceServer) GetServerToolPolicy(context.Context, *GetServerToolPolicyRequest) (*GetServerToolPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerToolPolicy not implemented")
}
func (UnimplementedChatServiceServer) SetServerToolPolicy(context.Context, *SetServerToolPolicyRequest) (*SetServerToolPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetServerToolPolicy not implemented")
}
func (UnimplementedChatServiceServer) GetAdminDashboard(context.Context, *GetAdminDashboardRequest) (*GetAdminDashboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdminDashboard not implemented")
}
func (UnimplementedChatServiceServer) GetSuperuserControlPlane(context.Context, *GetSuperuserControlPlaneRequest) (*GetSuperuserControlPlaneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuperuserControlPlane not implemented")
}
func (UnimplementedChatServiceServer) ListAdminUsers(context.Context, *ListAdminUsersRequest) (*ListAdminUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdminUsers not implemented")
}
func (UnimplementedChatServiceServer) ListAdminUsageEvents(context.Context, *ListAdminUsageEventsRequest) (*ListAdminUsageEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdminUsageEvents not implemented")
}
func (UnimplementedChatServiceServer) ListAdminConversations(context.Context, *ListAdminConversationsRequest) (*ListAdminConversationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdminConversations not implemented")
}
func (UnimplementedChatServiceServer) RunServerTool(grpc.BidiStreamingServer[RunServerToolRequest, RunServerToolEvent]) error {
	return status.Errorf(codes.Unimplemented, "method RunServerTool not implemented")
}
func (UnimplementedChatServiceServer) Send(*SendRequest, grpc.ServerStreamingServer[ChatChunk]) error {
	return status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedChatServiceServer) ListConversations(context.Context, *ListConversationsRequest) (*ListConversationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConversations not implemented")
}
func (UnimplementedChatServiceServer) ResolveConversationRoute(context.Context, *ResolveConversationRouteRequest) (*ResolveConversationRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveConversationRoute not implemented")
}
func (UnimplementedChatServiceServer) LoadConversation(context.Context, *LoadConversationRequest) (*LoadConversationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadConversation not implemented")
}
func (UnimplementedChatServiceServer) DeleteConversation(context.Context, *DeleteConversationRequest) (*DeleteConversationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConversation not implemented")
}
func (UnimplementedChatServiceServer) SetUserName(context.Context, *SetUserNameRequest) (*SetUserNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserName not implemented")
}
func (UnimplementedChatServiceServer) GetUserName(context.Context, *GetUserNameRequest) (*GetUserNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserName not implemented")
}
func (UnimplementedChatServiceServer) ListUserMemories(context.Context, *ListUserMemoriesRequest) (*ListUserMemoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserMemories not implemented")
}
func (UnimplementedChatServiceServer) UpsertUserMemory(context.Context, *UpsertUserMemoryRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertUserMemory not implemented")
}
func (UnimplementedChatServiceServer) DeleteUserMemory(context.Context, *DeleteUserMemoryRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserMemory not implemented")
}
func (UnimplementedChatServiceServer) SynthesizeSpeech(*SynthesizeSpeechRequest, grpc.ServerStreamingServer[SynthesizeSpeechChunk]) error {
	return status.Errorf(codes.Unimplemented, "method SynthesizeSpeech not implemented")
}
func (UnimplementedChatServiceServer) ListModelOptions(context.Context, *ListModelOptionsRequest) (*ListModelOptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModelOptions not implemented")
}
func (UnimplementedChatServiceServer) SetSelectedModel(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSelectedModel not implemented")
}
func (UnimplementedChatServiceServer) GetSelectedModel(context.Context, *emptypb.Empty) (*wrapperspb.StringValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSelectedModel not implemented")
}
func (UnimplementedChatServiceServer) SetSelectedTone(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSelectedTone not implemented")
}
func (UnimplementedChatServiceServer) GetSelectedTone(context.Context, *emptypb.Empty) (*wrapperspb.StringValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSelectedTone not implemented")
}
func (UnimplementedChatServiceServer) SetSelectedThinkingEnabled(context.Context, *wrapperspb.BoolValue) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSelectedThinkingEnabled not implemented")
}
func (UnimplementedChatServiceServer) GetSelectedThinkingEnabled(context.Context, *emptypb.Empty) (*wrapperspb.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSelectedThinkingEnabled not implemented")
}
func (UnimplementedChatServiceServer) SetSelectedThinkingEffort(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSelectedThinkingEffort not implemented")
}
func (UnimplementedChatServiceServer) GetSelectedThinkingEffort(context.Context, *emptypb.Empty) (*wrapperspb.StringValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSelectedThinkingEffort not implemented")
}
func (UnimplementedChatServiceServer) SetCustomSystemPrompt(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCustomSystemPrompt not implemented")
}
func (UnimplementedChatServiceServer) GetCustomSystemPrompt(context.Context, *emptypb.Empty) (*wrapperspb.StringValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomSystemPrompt not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}
func (UnimplementedChatServiceServer) testEmbeddedByValue()                     {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	// If the following call pancis, it indicates UnimplementedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_Signup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Logout(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetSession(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_RefreshSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).RefreshSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_RefreshSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).RefreshSession(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetClientIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetClientIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetClientIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetClientIdentity(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ReportClientLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportClientLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ReportClientLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ReportClientLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ReportClientLog(ctx, req.(*ReportClientLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetLogTail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogTailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetLogTail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetLogTail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetLogTail(ctx, req.(*GetLogTailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetServerToolPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerToolPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetServerToolPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetServerToolPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetServerToolPolicy(ctx, req.(*GetServerToolPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SetServerToolPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetServerToolPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SetServerToolPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SetServerToolPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SetServerToolPolicy(ctx, req.(*SetServerToolPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetAdminDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetAdminDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetAdminDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetAdminDashboard(ctx, req.(*GetAdminDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetSuperuserControlPlane_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSuperuserControlPlaneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetSuperuserControlPlane(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetSuperuserControlPlane_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetSuperuserControlPlane(ctx, req.(*GetSuperuserControlPlaneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ListAdminUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ListAdminUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ListAdminUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ListAdminUsers(ctx, req.(*ListAdminUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ListAdminUsageEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminUsageEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ListAdminUsageEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ListAdminUsageEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ListAdminUsageEvents(ctx, req.(*ListAdminUsageEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ListAdminConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminConversationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ListAdminConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ListAdminConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ListAdminConversations(ctx, req.(*ListAdminConversationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_RunServerTool_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServiceServer).RunServerTool(&grpc.GenericServerStream[RunServerToolRequest, RunServerToolEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_RunServerToolServer = grpc.BidiStreamingServer[RunServerToolRequest, RunServerToolEvent]

func _ChatService_Send_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SendRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).Send(m, &grpc.GenericServerStream[SendRequest, ChatChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_SendServer = grpc.ServerStreamingServer[ChatChunk]

func _ChatService_ListConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConversationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ListConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ListConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ListConversations(ctx, req.(*ListConversationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ResolveConversationRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveConversationRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ResolveConversationRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ResolveConversationRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ResolveConversationRoute(ctx, req.(*ResolveConversationRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_LoadConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).LoadConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_LoadConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).LoadConversation(ctx, req.(*LoadConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_DeleteConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).DeleteConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_DeleteConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).DeleteConversation(ctx, req.(*DeleteConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SetUserName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SetUserName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SetUserName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SetUserName(ctx, req.(*SetUserNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetUserName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetUserName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetUserName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetUserName(ctx, req.(*GetUserNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ListUserMemories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserMemoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ListUserMemories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ListUserMemories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ListUserMemories(ctx, req.(*ListUserMemoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_UpsertUserMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertUserMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).UpsertUserMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_UpsertUserMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).UpsertUserMemory(ctx, req.(*UpsertUserMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_DeleteUserMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).DeleteUserMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_DeleteUserMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).DeleteUserMemory(ctx, req.(*DeleteUserMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SynthesizeSpeech_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SynthesizeSpeechRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).SynthesizeSpeech(m, &grpc.GenericServerStream[SynthesizeSpeechRequest, SynthesizeSpeechChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_SynthesizeSpeechServer = grpc.ServerStreamingServer[SynthesizeSpeechChunk]

func _ChatService_ListModelOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ListModelOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_ListModelOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ListModelOptions(ctx, req.(*ListModelOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SetSelectedModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SetSelectedModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SetSelectedModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SetSelectedModel(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetSelectedModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetSelectedModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetSelectedModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetSelectedModel(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SetSelectedTone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SetSelectedTone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SetSelectedTone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SetSelectedTone(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetSelectedTone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetSelectedTone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetSelectedTone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetSelectedTone(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SetSelectedThinkingEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.BoolValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SetSelectedThinkingEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SetSelectedThinkingEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SetSelectedThinkingEnabled(ctx, req.(*wrapperspb.BoolValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetSelectedThinkingEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetSelectedThinkingEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetSelectedThinkingEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetSelectedThinkingEnabled(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SetSelectedThinkingEffort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SetSelectedThinkingEffort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SetSelectedThinkingEffort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SetSelectedThinkingEffort(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetSelectedThinkingEffort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetSelectedThinkingEffort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetSelectedThinkingEffort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetSelectedThinkingEffort(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SetCustomSystemPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SetCustomSystemPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SetCustomSystemPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SetCustomSystemPrompt(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetCustomSystemPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetCustomSystemPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetCustomSystemPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetCustomSystemPrompt(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.v1.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _ChatService_Signup_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _ChatService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _ChatService_Logout_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _ChatService_GetSession_Handler,
		},
		{
			MethodName: "RefreshSession",
			Handler:    _ChatService_RefreshSession_Handler,
		},
		{
			MethodName: "GetClientIdentity",
			Handler:    _ChatService_GetClientIdentity_Handler,
		},
		{
			MethodName: "ReportClientLog",
			Handler:    _ChatService_ReportClientLog_Handler,
		},
		{
			MethodName: "GetLogTail",
			Handler:    _ChatService_GetLogTail_Handler,
		},
		{
			MethodName: "GetServerToolPolicy",
			Handler:    _ChatService_GetServerToolPolicy_Handler,
		},
		{
			MethodName: "SetServerToolPolicy",
			Handler:    _ChatService_SetServerToolPolicy_Handler,
		},
		{
			MethodName: "GetAdminDashboard",
			Handler:    _ChatService_GetAdminDashboard_Handler,
		},
		{
			MethodName: "GetSuperuserControlPlane",
			Handler:    _ChatService_GetSuperuserControlPlane_Handler,
		},
		{
			MethodName: "ListAdminUsers",
			Handler:    _ChatService_ListAdminUsers_Handler,
		},
		{
			MethodName: "ListAdminUsageEvents",
			Handler:    _ChatService_ListAdminUsageEvents_Handler,
		},
		{
			MethodName: "ListAdminConversations",
			Handler:    _ChatService_ListAdminConversations_Handler,
		},
		{
			MethodName: "ListConversations",
			Handler:    _ChatService_ListConversations_Handler,
		},
		{
			MethodName: "ResolveConversationRoute",
			Handler:    _ChatService_ResolveConversationRoute_Handler,
		},
		{
			MethodName: "LoadConversation",
			Handler:    _ChatService_LoadConversation_Handler,
		},
		{
			MethodName: "DeleteConversation",
			Handler:    _ChatService_DeleteConversation_Handler,
		},
		{
			MethodName: "SetUserName",
			Handler:    _ChatService_SetUserName_Handler,
		},
		{
			MethodName: "GetUserName",
			Handler:    _ChatService_GetUserName_Handler,
		},
		{
			MethodName: "ListUserMemories",
			Handler:    _ChatService_ListUserMemories_Handler,
		},
		{
			MethodName: "UpsertUserMemory",
			Handler:    _ChatService_UpsertUserMemory_Handler,
		},
		{
			MethodName: "DeleteUserMemory",
			Handler:    _ChatService_DeleteUserMemory_Handler,
		},
		{
			MethodName: "ListModelOptions",
			Handler:    _ChatService_ListModelOptions_Handler,
		},
		{
			MethodName: "SetSelectedModel",
			Handler:    _ChatService_SetSelectedModel_Handler,
		},
		{
			MethodName: "GetSelectedModel",
			Handler:    _ChatService_GetSelectedModel_Handler,
		},
		{
			MethodName: "SetSelectedTone",
			Handler:    _ChatService_SetSelectedTone_Handler,
		},
		{
			MethodName: "GetSelectedTone",
			Handler:    _ChatService_GetSelectedTone_Handler,
		},
		{
			MethodName: "SetSelectedThinkingEnabled",
			Handler:    _ChatService_SetSelectedThinkingEnabled_Handler,
		},
		{
			MethodName: "GetSelectedThinkingEnabled",
			Handler:    _ChatService_GetSelectedThinkingEnabled_Handler,
		},
		{
			MethodName: "SetSelectedThinkingEffort",
			Handler:    _ChatService_SetSelectedThinkingEffort_Handler,
		},
		{
			MethodName: "GetSelectedThinkingEffort",
			Handler:    _ChatService_GetSelectedThinkingEffort_Handler,
		},
		{
			MethodName: "SetCustomSystemPrompt",
			Handler:    _ChatService_SetCustomSystemPrompt_Handler,
		},
		{
			MethodName: "GetCustomSystemPrompt",
			Handler:    _ChatService_GetCustomSystemPrompt_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunServerTool",
			Handler:       _ChatService_RunServerTool_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Send",
			Handler:       _ChatService_Send_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SynthesizeSpeech",
			Handler:       _ChatService_SynthesizeSpeech_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/chat.proto",
}
