package interop

import (
	"encoding/base64"
	"errors"
	"strings"
)

// CryptoKey is an opaque handle wrapping a non-extractable AES-GCM key
// generated by the browser's WebCrypto API. On native builds the underlying
// field is always nil; on WASM builds it holds the live js.Value.
type CryptoKey struct {
	// raw holds the underlying js.Value on WASM; nil elsewhere. The type is
	// `any` so this file compiles without a build tag.
	raw any //nolint:unused // read by crypto_wasm.go; native lint cannot see it
}

// EncryptedStore combines a CryptoKey with a Storage backend to provide
// transparent JSON-marshal-then-encrypt persistence. Values are stored as a
// base64-encoded envelope: "<base64(iv)>:<base64(ciphertext)>".
type EncryptedStore struct {
	key     CryptoKey //nolint:unused // read by crypto_wasm.go; native lint cannot see it
	storage Storage   //nolint:unused // read by crypto_wasm.go; native lint cannot see it
}

// encodeEnvelope encodes an IV and ciphertext into the "<b64iv>:<b64ct>"
// envelope string stored in LocalStorage.
func encodeEnvelope(parseIV []byte, parseCiphertext []byte) string {
	parseB64IV := base64.StdEncoding.EncodeToString(parseIV)
	parseB64CT := base64.StdEncoding.EncodeToString(parseCiphertext)
	return parseB64IV + ":" + parseB64CT
}

// decodeEnvelope reverses encodeEnvelope. It returns a structured error when
// the envelope is malformed or either segment is not valid base64 — a tampered
// or garbage stored value will never silently decode.
func decodeEnvelope(parseEnvelope string) (parseIV []byte, parseCiphertext []byte, parseErr error) {
	before, after, ok := strings.Cut(parseEnvelope, ":")
	if !ok {
		return nil, nil, wrapError("decodeEnvelope", "", CodeDecode, errors.New("missing iv:ciphertext separator"))
	}
	parseIV, parseErr = base64.StdEncoding.DecodeString(before)
	if parseErr != nil {
		return nil, nil, wrapError("decodeEnvelope", "", CodeDecode, parseErr)
	}
	parseCiphertext, parseErr = base64.StdEncoding.DecodeString(after)
	if parseErr != nil {
		return nil, nil, wrapError("decodeEnvelope", "", CodeDecode, parseErr)
	}
	return parseIV, parseCiphertext, nil
}
