package ui

import (
	"strconv"
	"strings"
)

// CSSEscape escapes a string for safe use as a CSS identifier, implementing the
// WHATWG CSS.escape algorithm (https://drafts.csswg.org/cssom/#serialize-an-identifier).
//
// Element ids returned by [UseId] are already CSS-safe by construction (see G29),
// so escaping them is unnecessary. CSSEscape exists for the general case: any id
// derived from user data, external systems, or string concatenation that is then
// fed into a CSS selector. Use it together with [SelectorID]:
//
//	node := document.Call("querySelector", ui.SelectorID(userProvidedID))
//
// Passing an un-escaped arbitrary string to querySelector("#"+id) can throw a
// SyntaxError (and, in a wasm callback, panic the page) when the id contains a
// colon, space, or other CSS metacharacter.
func CSSEscape(parseValue string) string {
	if parseValue == "" {
		return ""
	}

	var parseBuilder strings.Builder
	parseBuilder.Grow(len(parseValue))

	parseRunes := []rune(parseValue)
	for parseIndex, parseCh := range parseRunes {
		switch {
		case parseCh == 0:
			// NULL becomes the replacement character.
			parseBuilder.WriteRune('�')
		case (parseCh >= 0x0001 && parseCh <= 0x001F) || parseCh == 0x007F:
			// Control characters are escaped as a code point.
			writeCSSCodePoint(&parseBuilder, parseCh)
		case parseIndex == 0 && parseCh >= '0' && parseCh <= '9':
			// A leading digit is escaped as a code point.
			writeCSSCodePoint(&parseBuilder, parseCh)
		case parseIndex == 1 && parseRunes[0] == '-' && parseCh >= '0' && parseCh <= '9':
			// A digit immediately following a leading hyphen is escaped.
			writeCSSCodePoint(&parseBuilder, parseCh)
		case parseIndex == 0 && parseCh == '-' && len(parseRunes) == 1:
			// A lone leading hyphen is backslash-escaped.
			parseBuilder.WriteByte('\\')
			parseBuilder.WriteRune(parseCh)
		case parseCh >= 0x0080 || parseCh == '-' || parseCh == '_' ||
			(parseCh >= '0' && parseCh <= '9') ||
			(parseCh >= 'a' && parseCh <= 'z') ||
			(parseCh >= 'A' && parseCh <= 'Z'):
			// Identifier-safe code points are emitted verbatim.
			parseBuilder.WriteRune(parseCh)
		default:
			// Everything else is backslash-escaped.
			parseBuilder.WriteByte('\\')
			parseBuilder.WriteRune(parseCh)
		}
	}

	return parseBuilder.String()
}

// writeCSSCodePoint writes a CSS code-point escape: a backslash, the lowercase
// hex value, and a trailing space.
func writeCSSCodePoint(parseBuilder *strings.Builder, parseCh rune) {
	parseBuilder.WriteByte('\\')
	parseBuilder.WriteString(strconv.FormatInt(int64(parseCh), 16))
	parseBuilder.WriteByte(' ')
}

// SelectorID returns a CSS id selector ("#" + escaped id) for the given element
// id, safe to pass to querySelector/querySelectorAll for an id from any source.
//
//	el := document.Call("querySelector", ui.SelectorID(id))
//
// For ids generated by [UseId] the escaping is a no-op, but using SelectorID
// everywhere keeps call sites uniformly safe.
func SelectorID(parseID string) string {
	return "#" + CSSEscape(parseID)
}
